<a href="https://colab.research.google.com/github/Saifullah785/machine-learning-engineer-roadmap/blob/main/Lecture_78_Optuna_Basics_yt/Lecture_78_Optuna_Basics_yt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Install Optuna library
!pip install optuna

Collecting optuna
  Downloading optuna-4.5.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.16.5)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.43)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Downloading optuna-4.5.0-py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 8.1 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.9.0 optuna-4.5.0

In [ ]:
# Import necessary libraries for model training and hyperparameter tuning
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
# Load the Pima Indian Diabetes dataset from a URL
import pandas as pd
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

In [ ]:
# Load the dataset into a pandas DataFrame and display the head
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
# Handle missing values by replacing zeros with NaN and imputing with the mean
import numpy as np

# Replace zero values with NaN is columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

#check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
# Split the data into training and test sets and scale the features
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [ ]:
# Define the objective function for Optuna to optimize RandomForest hyperparameters
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

#Define the objective function
def objective(trial):
  # Suggest values for the hyperparameters
  n_estimators = trial.suggest_int('n_estimators',  50, 200)
  max_depth = trial.suggest_int('max_depth', 3, 20)

  # create the randomForestClassifier with suggested hyperparameters
  model = RandomForestClassifier(
      n_estimators=n_estimators,
      max_depth=max_depth,
      random_state=42
  )
  # Perform 3-fold cross-validation and calculate accuracy
  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

  return score

In [ ]:
# Create and run an Optuna study to find the best hyperparameters for RandomForest
# create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler()) # we aim to maximize accuracy

# RUn 50 trials to find the best hyperparameters
study.optimize(objective, n_trials=50)

[I 2025-09-12 06:27:57,880] A new study created in memory with name: no-name-865c2f04-c90c-4b59-bf34-34328ddbd700
[I 2025-09-12 06:27:58,682] Trial 0 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 63, 'max_depth': 4}. Best is trial 0 with value: 0.7597765363128491.
[I 2025-09-12 06:28:00,225] Trial 1 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 143, 'max_depth': 15}. Best is trial 1 with value: 0.7709497206703911.
[I 2025-09-12 06:28:01,684] Trial 2 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 130, 'max_depth': 6}. Best is trial 1 with value: 0.7709497206703911.
[I 2025-09-12 06:28:03,218] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 20}. Best is trial 1 with value: 0.7709497206703911.
[I 2025-09-12 06:28:04,245] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 56, 'max_depth': 20}. Best is trial 1 with value: 0.7709497206703911.
[I 2025-09-12 06:28:05,558] Trial 5 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 109, 'max_depth': 7}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:08,085] Trial 6 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 167, 'max_depth': 17}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:09,807] Trial 7 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 129, 'max_depth': 9}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:10,892] Trial 8 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 57, 'max_depth': 17}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:13,251] Trial 9 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 102, 'max_depth': 16}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:15,956] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 199, 'max_depth': 10}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:17,827] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 179, 'max_depth': 13}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:18,861] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 96, 'max_depth': 7}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:19,793] Trial 13 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 162, 'max_depth': 12}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:20,265] Trial 14 finished with value: 0.756052141527002 and parameters: {'n_estimators': 92, 'max_depth': 3}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:20,912] Trial 15 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 109, 'max_depth': 9}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:21,917] Trial 16 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 176, 'max_depth': 14}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:22,801] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 155, 'max_depth': 18}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:23,428] Trial 18 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 117, 'max_depth': 6}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:23,931] Trial 19 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 81, 'max_depth': 11}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:25,528] Trial 20 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 188, 'max_depth': 8}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:26,199] Trial 21 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 72, 'max_depth': 17}. Best is trial 21 with value: 0.7783985102420856.
[I 2025-09-12 06:28:26,851] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 77, 'max_depth': 18}. Best is trial 21 with value: 0.7783985102420856.
[I 2025-09-12 06:28:27,286] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 74, 'max_depth': 15}. Best is trial 21 with value: 0.7783985102420856.
[I 2025-09-12 06:28:27,980] Trial 24 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 119, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:28,683] Trial 25 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 119, 'max_depth': 20}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:29,501] Trial 26 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 139, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:30,214] Trial 27 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 120, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:30,739] Trial 28 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 90, 'max_depth': 20}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:31,161] Trial 29 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 70, 'max_depth': 17}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:31,465] Trial 30 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 18}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:31,887] Trial 31 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 72, 'max_depth': 16}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:32,400] Trial 32 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 84, 'max_depth': 16}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:32,792] Trial 33 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:33,183] Trial 34 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:33,972] Trial 35 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 20}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:34,834] Trial 36 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 149, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:35,238] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 65, 'max_depth': 14}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:35,859] Trial 38 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 18}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:36,575] Trial 39 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 122, 'max_depth': 20}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:37,714] Trial 40 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 128, 'max_depth': 20}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:38,379] Trial 41 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 71, 'max_depth': 17}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:38,926] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 56, 'max_depth': 17}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:39,509] Trial 43 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 66, 'max_depth': 15}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:40,016] Trial 44 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 87, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:40,322] Trial 45 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 17}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:40,904] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 99, 'max_depth': 16}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:41,583] Trial 47 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 113, 'max_depth': 18}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:42,188] Trial 48 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 103, 'max_depth': 14}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:42,864] Trial 49 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 115, 'max_depth': 18}. Best is trial 24 with value: 0.7821229050279329.

In [ ]:
# Print the best trial's accuracy and hyperparameters for RandomForest
# print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 119, 'max_depth': 19}

In [ ]:
# Train and evaluate the RandomForest model with the best hyperparameters
from sklearn.metrics import accuracy_score

#  Train a RandomForestClassifier using the best hyperparameters from optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# print the test acccuracy

print(f'Test accuracy with best hyperparameters: {test_accuracy:.2f}')

Test accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [ ]:
# Import visualization functions from Optuna
# For visualizations

from optuna.visualization import plot_optimization_history, \
plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [ ]:
# Plot the optimization history of the Optuna study
# 1. Optimization History
plot_optimization_history(study).show()

In [ ]:
# Plot the parallel coordinates of the Optuna study
# 2. parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [ ]:
# Plot the slice plot of the Optuna study
# 3.Slice Plot
plot_slice(study).show()

In [ ]:
# Plot the contour plot of the Optuna study
# 4. Contour Plot
plot_contour(study).show()

In [ ]:
# Plot the parameter importances of the Optuna study
# 5. Parameter Importances Plot
plot_param_importances(study).show()

# Optimizing Mulitple ML Models

In [ ]:
# Import additional classifiers for multi-model optimization
# importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [ ]:
# Define the objective function for Optuna to optimize multiple classifiers
# Define the objective function for Optuna
def objective(trial):
  # Choose the algorithm to tune
  classifier_name = trial.suggest_categorical('classifier', ['SVM','RandomForest', 'GradientBoosting'])
  if classifier_name == 'SVM':
    # Suggest hyperparameters for SVM
    c = trial.suggest_float('C', 0.1, 100, log =True)
    kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
    gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])
    model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

  elif classifier_name == 'RandomForest':
    # Suggest hyperparameters for RandomForest
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
    bootstrap = trial.suggest_categorical('bootstrap', [True, False])

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        bootstrap=bootstrap,
        random_state=42
    )

  elif classifier_name == 'GradientBoosting':
    # Suggest hyperparameters for GradientBoosting
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    learning_rate = trial.suggest_float('learning_rat', 0.01, 0.3, log=True)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

    model = GradientBoostingClassifier(
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        random_state=42
    )
  # Perform cross-validation and return the mean accuracy
  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
  return score

In [ ]:
# Create and run an Optuna study to optimize multiple classifiers
# create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-09-12 06:30:45,347] A new study created in memory with name: no-name-7cebbe86-1190-4974-9237-48d0e55ccf4e
[I 2025-09-12 06:30:45,385] Trial 0 finished with value: 0.7597765363128491 and parameters: {'classifier': 'SVM', 'C': 6.646123816110229, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 0 with value: 0.7597765363128491.
[I 2025-09-12 06:30:45,417] Trial 1 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.7735524248608444, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:46,692] Trial 2 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 257, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:46,969] Trial 3 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 53, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:51,698] Trial 4 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 295, 'learning_rat': 0.17063274664740466, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:55,157] Trial 5 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 252, 'learning_rat': 0.022946348411111907, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 7}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:56,435] Trial 6 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 246, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:56,465] Trial 7 finished with value: 0.6871508379888268 and parameters: {'classifier': 'SVM', 'C': 11.603742463206638, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:58,121] Trial 8 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 294, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:59,415] Trial 9 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 94, 'learning_rat': 0.04469354079007895, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:59,447] Trial 10 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 0.11762066010350415, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:59,483] Trial 11 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.31476985723821327, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:59,792] Trial 12 finished with value: 0.7541899441340782 and parameters: {'classifier': 'RandomForest', 'n_estimators': 56, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:31:00,421] Trial 13 finished with value: 0.7765363128491619 and parameters: {'classifier': 'RandomForest', 'n_estimators': 145, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 13 with value: 0.7765363128491619.
[I 2025-09-12 06:31:00,454] Trial 14 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.9953742390783178, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7839851024208566.
[I 2025-09-12 06:31:01,117] Trial 15 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 150, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 14 with value: 0.7839851024208566.
[I 2025-09-12 06:31:01,565] Trial 16 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 60.37330182928018, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:02,142] Trial 17 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 89.46612661404423, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:02,579] Trial 18 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 66.77361414390164, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:03,308] Trial 19 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 97.50267032585099, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:03,475] Trial 20 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 22.334622441146127, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:03,842] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 82.33713286916257, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:03,992] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 37.008676058327914, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:04,141] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 31.97044268923693, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:04,493] Trial 24 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 96.39540484336777, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:04,571] Trial 25 finished with value: 0.702048417132216 and parameters: {'classifier': 'SVM', 'C': 42.12929382858266, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:07,409] Trial 26 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 198, 'learning_rat': 0.01035302908911959, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:07,444] Trial 27 finished with value: 0.6945996275605214 and parameters: {'classifier': 'SVM', 'C': 10.842948674926099, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:07,550] Trial 28 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 20.433752767304423, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:07,598] Trial 29 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.994493904144414, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:07,784] Trial 30 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 46.61710722131724, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:08,159] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.53630784069209, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:08,395] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 61.45197525121031, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:08,621] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 54.54554028179222, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:08,762] Trial 34 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 23.008878799932226, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:08,909] Trial 35 finished with value: 0.6741154562383613 and parameters: {'classifier': 'SVM', 'C': 96.71085727184952, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:11,507] Trial 36 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 189, 'learning_rat': 0.19783532514903548, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:11,541] Trial 37 finished with value: 0.6927374301675977 and parameters: {'classifier': 'SVM', 'C': 54.517525006722096, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:11,643] Trial 38 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 19.636520400112303, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,086] Trial 39 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 108, 'learning_rat': 0.07366619579994482, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,169] Trial 40 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 11.963254120505741, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,306] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 27.659692009802733, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,564] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 61.16406217414533, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,879] Trial 43 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 61.74025734446257, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,956] Trial 44 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 36.7064722865805, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:14,045] Trial 45 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.373780260390611, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:15,543] Trial 46 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 219, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:17,789] Trial 47 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 148, 'learning_rat': 0.011867099717722908, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:17,828] Trial 48 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 1.9953808082806745, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:18,235] Trial 49 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 102, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:18,495] Trial 50 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 70.51707637355395, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:18,959] Trial 51 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.18887438778975, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,247] Trial 52 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 73.12639238186472, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,282] Trial 53 finished with value: 0.6871508379888268 and parameters: {'classifier': 'SVM', 'C': 32.711075927574605, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,373] Trial 54 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 13.71560895142646, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,453] Trial 55 finished with value: 0.7039106145251397 and parameters: {'classifier': 'SVM', 'C': 40.5790874132925, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,897] Trial 56 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 76.36681988712974, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,945] Trial 57 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 45.80042084353926, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:21,137] Trial 58 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 219, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:22,192] Trial 59 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 124, 'learning_rat': 0.2945856647531005, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:22,223] Trial 60 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17554053303993863, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 60 with value: 0.7877094972067038.
[I 2025-09-12 06:31:22,253] Trial 61 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23600686192855178, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 60 with value: 0.7877094972067038.
[I 2025-09-12 06:31:22,282] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1487410667880136, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,312] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1367026698691512, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,341] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13898136166708, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,369] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1226876477944892, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,400] Trial 66 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11239694333157642, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,432] Trial 67 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1093096740042429, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,464] Trial 68 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1141385271194235, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,497] Trial 69 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17066851296467678, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,532] Trial 70 finished with value: 0.7430167597765364 and parameters: {'classifier': 'SVM', 'C': 0.5030886123553856, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,563] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12178451340246961, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,593] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15167079583859197, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,624] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14688777215645402, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,656] Trial 74 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.30931290314473386, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,701] Trial 75 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.10493310590162029, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,733] Trial 76 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21912494921911677, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:23,162] Trial 77 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 76, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:23,194] Trial 78 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1373761673164917, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:23,229] Trial 79 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4090721541288155, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:26,640] Trial 80 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 174, 'learning_rat': 0.0754831565387224, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:26,687] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14138942804209903, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.

In [ ]:
# Retrieve and print the best trial's accuracy and hyperparameters for multi-model optimization
# Retrieve the best trial
best_trial = study.best_trial

# Print the best trial's accuracy and hyperparameters
print(f'Best trial accuracy: {best_trial.value}')
print(f'Best hyperparameters: {best_trial.params}')

Best trial accuracy: 0.7895716945996275
Best hyperparameters: {'classifier': 'SVM', 'C': 0.1487410667880136, 'kernel': 'linear', 'gamma': 'scale'}

In [ ]:
# Display the dataframe of trials from the Optuna study
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rat,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.759777,2025-09-12 06:30:45.349511,2025-09-12 06:30:45.385290,0 days 00:00:00.035779,6.646124,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.767225,2025-09-12 06:30:45.386368,2025-09-12 06:30:45.417134,0 days 00:00:00.030766,0.773552,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.763501,2025-09-12 06:30:45.418052,2025-09-12 06:30:46.692297,0 days 00:00:01.274245,NaN,False,RandomForest,NaN,NaN,NaN,20.0,2.0,5.0,257.0,COMPLETE
3,3,0.767225,2025-09-12 06:30:46.693663,2025-09-12 06:30:46.969502,0 days 00:00:00.275839,NaN,True,RandomForest,NaN,NaN,NaN,16.0,10.0,9.0,53.0,COMPLETE
4,4,0.741155,2025-09-12 06:30:46.970421,2025-09-12 06:30:51.698354,0 days 00:00:04.727933,NaN,NaN,GradientBoosting,NaN,NaN,0.170633,17.0,2.0,4.0,295.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.783985,2025-09-12 06:31:28.033976,2025-09-12 06:31:28.078552,0 days 00:00:00.044576,0.442434,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.765363,2025-09-12 06:31:28.079714,2025-09-12 06:31:28.146418,0 days 00:00:00.066704,0.249105,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.772812,2025-09-12 06:31:28.147633,2025-09-12 06:31:30.252758,0 days 00:00:02.105125,NaN,False,RandomForest,NaN,NaN,NaN,10.0,8.0,9.0,276.0,COMPLETE
98,98,0.711359,2025-09-12 06:31:30.253695,2025-09-12 06:31:30.301175,0 days 00:00:00.047480,0.124737,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.767225,2025-09-12 06:31:30.302003,2025-09-12 06:31:32.796765,0 days 00:00:02.494762,NaN,NaN,GradientBoosting,NaN,NaN,0.028623,6.0,3.0,3.0,232.0,COMPLETE

In [ ]:
# Count the number of trials for each classifier in the study
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 78
RandomForest        12
GradientBoosting    10
Name: count, dtype: int64

In [ ]:
# Calculate and display the mean accuracy for each classifier in the study
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.745624
RandomForest        0.765673
SVM                 0.772334
Name: value, dtype: float64

In [ ]:
# Plot the optimization history of the multi-model Optuna study
# 1.Optimization History
plot_optimization_history(study).show()

In [ ]:
# Plot the slice plot of the multi-model Optuna study
# 3.Slice plot
plot_slice(study).show()

In [ ]:
# Plot the hyperparameter importances of the multi-model Optuna study
# 5. hyperparameter importance
plot_param_importances(study).show()

In [3]:
# Install Optuna library
!pip install optuna

Collecting optuna
  Downloading optuna-4.5.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.16.5)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.43)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Downloading optuna-4.5.0-py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 7.7 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.9.0 optuna-4.5.0

In [17]:
# Import necessary libraries for XGBoost optimization
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

In [18]:
# Load and split the Iris dataset
# Load the iris dataset
X,y = load_iris(return_X_y=True)


# split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
# Define the objective function for XGBoost hyperparameter tuning with pruning
# Define the objective function for XGBoost
def objective(trail):
  # Hyperparameter search space
  param = {
      'verbosity': 0,
      'objective': 'multi:softprob',
      'num_class': 3,
      'eval_metric': 'mlogloss', # Ensure that the eval_metric is specified here
      'booster': 'gbtree',
      'lambda': trail.suggest_float('lambda', 1e-8, 1.0, log=True),
      'alpha': trail.suggest_float('alpha', 1e-8, 1.0, log=True),
      'eta': trail.suggest_float('eta', 0.01, 0.3),
      'gamma': trail.suggest_float('gamma', 1e-8, 1.0, log=True),
      'max_depth': trail.suggest_int('max_depth', 3, 9),
      'min_child_weight': trail.suggest_int('min_child_weight', 1, 10),
      'subsample': trail.suggest_float('subsample', 0.4, 1.0),
      'colsample_bytree': trail.suggest_float('colsample_bytree', 0.4, 1.0),
      'n_estimators': 300,
  }
  # Create DMatrix for XGBoost
  dtrain = xgb.DMatrix(X_train, label=y_train)
  dtest = xgb.DMatrix(X_test, label=y_test)

  # Define a pruning callback based on evaluation metrics
  pruning_callback = optuna.integration.XGBoostPruningCallback(trail, "eval-mlogloss") # match the metric name in the evals list

  # Train the model
  bst = xgb.train(
      param,
      dtrain,
      num_boost_round=300,
      evals=[(dtrain,'train'), (dtest, 'eval')],
      early_stopping_rounds=10,
      callbacks=[pruning_callback]

  )
  # predict on the test set
  preds = bst.predict(dtest)
  best_preds = [int(np.argmax(line)) for line in preds]

  # Return accuracy as the objective value
  accuracy = accuracy_score(y_test, best_preds)
  return accuracy

In [20]:
# Create and run an Optuna study with pruning for XGBoost optimization
# create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

[I 2025-09-13 06:38:38,643] A new study created in memory with name: no-name-4eee5bac-1294-43e0-973e-d6de01d33708

[0]	train-mlogloss:0.95053	eval-mlogloss:0.94150
[1]	train-mlogloss:0.83052	eval-mlogloss:0.81590
[2]	train-mlogloss:0.73175	eval-mlogloss:0.71306
[3]	train-mlogloss:0.64655	eval-mlogloss:0.62338
[4]	train-mlogloss:0.57698	eval-mlogloss:0.55095
[5]	train-mlogloss:0.51344	eval-mlogloss:0.48336
[6]	train-mlogloss:0.46104	eval-mlogloss:0.42763
[7]	train-mlogloss:0.41854	eval-mlogloss:0.38368
[8]	train-mlogloss:0.38221	eval-mlogloss:0.34377
[9]	train-mlogloss:0.35061	eval-mlogloss:0.30814
[10]	train-mlogloss:0.32279	eval-mlogloss:0.27652
[11]	train-mlogloss:0.29827	eval-mlogloss:0.24916
[12]	train-mlogloss:0.27726	eval-mlogloss:0.22771
[13]	train-mlogloss:0.25965	eval-mlogloss:0.20878
[14]	train-mlogloss:0.24195	eval-mlogloss:0.18944
[15]	train-mlogloss:0.22824	eval-mlogloss:0.17378
[16]	train-mlogloss:0.21716	eval-mlogloss:0.16207
[17]	train-mlogloss:0.20564	eval-mlogloss:0.14943
[18]	train-mlogloss:0.19735	eval-mlogloss:0.14013
[19]	train-mlogloss:0.18953	eval-mlogloss:0.13148
[20]	train-mlogloss:0.18319	eval-mlogloss:0.12433
[21]	train-mlogloss:0.17813	eval-mlogloss:0.11858
[22]	train-mlogloss:0.17588	eval-mlogloss:0.11545
[23]	train-mlogloss:0.16994	eval-mlogloss:0.10917
[24]	train-mlogloss:0.16661	eval-mlogloss:0.10541
[25]	train-mlogloss:0.16461	eval-mlogloss:0.10256
[26]	train-mlogloss:0.16307	eval-mlogloss:0.10044
[27]	train-mlogloss:0.16258	eval-mlogloss:0.10046
[28]	train-mlogloss:0.16159	eval-mlogloss:0.09915
[29]	train-mlogloss:0.16065	eval-mlogloss:0.09772
[30]	train-mlogloss:0.15885	eval-mlogloss:0.09648
[31]	train-mlogloss:0.15695	eval-mlogloss:0.09428
[32]	train-mlogloss:0.15681	eval-mlogloss:0.09432
[33]	train-mlogloss:0.15430	eval-mlogloss:0.09083
[34]	train-mlogloss:0.15334	eval-mlogloss:0.08928
[35]	train-mlogloss:0.15321	eval-mlogloss:0.08928
[36]	train-mlogloss:0.15315	eval-mlogloss:0.08929
[37]	train-mlogloss:0.15230	eval-mlogloss:0.08821
[38]	train-mlogloss:0.15186	eval-mlogloss:0.08855
[39]	train-mlogloss:0.15186	eval-mlogloss:0.08854
[40]	train-mlogloss:0.15136	eval-mlogloss:0.08825
[41]	train-mlogloss:0.15038	eval-mlogloss:0.08666
[42]	train-mlogloss:0.15032	eval-mlogloss:0.08658
[43]	train-mlogloss:0.15004	eval-mlogloss:0.08615
[44]	train-mlogloss:0.15001	eval-mlogloss:0.08568
[45]	train-mlogloss:0.14982	eval-mlogloss:0.08554
[46]	train-mlogloss:0.14961	eval-mlogloss:0.08507
[47]	train-mlogloss:0.14944	eval-mlogloss:0.08525
[48]	train-mlogloss:0.14946	eval-mlogloss:0.08532
[49]	train-mlogloss:0.14821	eval-mlogloss:0.08378
[50]	train-mlogloss:0.14704	eval-mlogloss:0.08199
[51]	train-mlogloss:0.14691	eval-mlogloss:0.08154
[52]	train-mlogloss:0.14681	eval-mlogloss:0.08154
[53]	train-mlogloss:0.14681	eval-mlogloss:0.08154
[54]	train-mlogloss:0.14679	eval-mlogloss:0.08151
[55]	train-mlogloss:0.14642	eval-mlogloss:0.08111
[56]	train-mlogloss:0.14642	eval-mlogloss:0.08119
[57]	train-mlogloss:0.14639	eval-mlogloss:0.08098
[58]	train-mlogloss:0.14605	eval-mlogloss:0.08026
[59]	train-mlogloss:0.14582	eval-mlogloss:0.08013
[60]	train-mlogloss:0.14493	eval-mlogloss:0.08041
[61]	train-mlogloss:0.14473	eval-mlogloss:0.08032
[62]	train-mlogloss:0.14444	eval-mlogloss:0.08040
[63]	train-mlogloss:0.14439	eval-mlogloss:0.07975
[64]	train-mlogloss:0.14437	eval-mlogloss:0.07952
[65]	train-mlogloss:0.14443	eval-mlogloss:0.07960
[66]	train-mlogloss:0.14443	eval-mlogloss:0.07955
[67]	train-mlogloss:0.14442	eval-mlogloss:0.07962
[68]	train-mlogloss:0.14386	eval-mlogloss:0.07992
[69]	train-mlogloss:0.14351	eval-mlogloss:0.07919
[70]	train-mlogloss:0.14348	eval-mlogloss:0.07921
[71]	train-mlogloss:0.14345	eval-mlogloss:0.07905
[72]	train-mlogloss:0.14345	eval-mlogloss:0.07898
[73]	train-mlogloss:0.14341	eval-mlogloss:0.07888
[74]	train-mlogloss:0.14341	eval-mlogloss:0.07881
[75]	train-mlogloss:0.14341	eval-mlogloss:0.07889
[76]	train-mlogloss:0.14343	eval-mlogloss:0.07899
[77]	train-mlogloss:0.14341	eval-mlogloss:0.07897
[78]	train-mlogloss:0.14335	eval-mlogloss:0.07896
[79]	train-mlogloss:0.14335	eval-mlogloss:0.07896
[80]	train-mlogloss:0.14335	eval-mlogloss:0.07896
[81]	train-mlogloss:0.14333	eval-mlogloss:0.07894
[82]	train-mlogloss:0.14270	eval-mlogloss:0.07948
[83]	train-mlogloss:0.14276	eval-mlogloss:0.07980

[I 2025-09-13 06:38:38,848] Trial 0 finished with value: 1.0 and parameters: {'lambda': 1.1471264413212224e-05, 'alpha': 0.6659164267864843, 'eta': 0.12761709167928534, 'gamma': 7.3584050263077905e-06, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.5835119912379031, 'colsample_bytree': 0.7711561376974307}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.04006	eval-mlogloss:1.04441
[1]	train-mlogloss:0.91165	eval-mlogloss:0.90619
[2]	train-mlogloss:0.80941	eval-mlogloss:0.79978
[3]	train-mlogloss:0.74081	eval-mlogloss:0.71998
[4]	train-mlogloss:0.68036	eval-mlogloss:0.65854
[5]	train-mlogloss:0.61225	eval-mlogloss:0.58394
[6]	train-mlogloss:0.56676	eval-mlogloss:0.53429
[7]	train-mlogloss:0.53879	eval-mlogloss:0.51404
[8]	train-mlogloss:0.49568	eval-mlogloss:0.46486
[9]	train-mlogloss:0.46171	eval-mlogloss:0.42969
[10]	train-mlogloss:0.42896	eval-mlogloss:0.38882
[11]	train-mlogloss:0.40733	eval-mlogloss:0.36628
[12]	train-mlogloss:0.39813	eval-mlogloss:0.35767
[13]	train-mlogloss:0.37076	eval-mlogloss:0.32757
[14]	train-mlogloss:0.36376	eval-mlogloss:0.31959
[15]	train-mlogloss:0.35714	eval-mlogloss:0.31250
[16]	train-mlogloss:0.34664	eval-mlogloss:0.29824
[17]	train-mlogloss:0.33897	eval-mlogloss:0.28981
[18]	train-mlogloss:0.33335	eval-mlogloss:0.28628
[19]	train-mlogloss:0.33186	eval-mlogloss:0.28440
[20]	train-mlogloss:0.32454	eval-mlogloss:0.27746
[21]	train-mlogloss:0.31621	eval-mlogloss:0.26965
[22]	train-mlogloss:0.30913	eval-mlogloss:0.25962
[23]	train-mlogloss:0.30288	eval-mlogloss:0.25040
[24]	train-mlogloss:0.30303	eval-mlogloss:0.25051
[25]	train-mlogloss:0.29565	eval-mlogloss:0.24198
[26]	train-mlogloss:0.29421	eval-mlogloss:0.24007
[27]	train-mlogloss:0.29361	eval-mlogloss:0.23968
[28]	train-mlogloss:0.29354	eval-mlogloss:0.23978
[29]	train-mlogloss:0.29350	eval-mlogloss:0.23980
[30]	train-mlogloss:0.29365	eval-mlogloss:0.24022
[31]	train-mlogloss:0.29273	eval-mlogloss:0.23885
[32]	train-mlogloss:0.29263	eval-mlogloss:0.23880
[33]	train-mlogloss:0.29265	eval-mlogloss:0.23856
[34]	train-mlogloss:0.29206	eval-mlogloss:0.23784
[35]	train-mlogloss:0.29126	eval-mlogloss:0.23757
[36]	train-mlogloss:0.28518	eval-mlogloss:0.23137
[37]	train-mlogloss:0.28462	eval-mlogloss:0.23223
[38]	train-mlogloss:0.28458	eval-mlogloss:0.23230
[39]	train-mlogloss:0.28364	eval-mlogloss:0.23114
[40]	train-mlogloss:0.28324	eval-mlogloss:0.22982
[41]	train-mlogloss:0.28274	eval-mlogloss:0.22908
[42]	train-mlogloss:0.28228	eval-mlogloss:0.22760
[43]	train-mlogloss:0.28239	eval-mlogloss:0.22779
[44]	train-mlogloss:0.28235	eval-mlogloss:0.22773
[45]	train-mlogloss:0.28186	eval-mlogloss:0.22721
[46]	train-mlogloss:0.28191	eval-mlogloss:0.22684
[47]	train-mlogloss:0.28168	eval-mlogloss:0.22627
[48]	train-mlogloss:0.27956	eval-mlogloss:0.22339
[49]	train-mlogloss:0.27864	eval-mlogloss:0.22222
[50]	train-mlogloss:0.27250	eval-mlogloss:0.21426
[51]	train-mlogloss:0.27253	eval-mlogloss:0.21428
[52]	train-mlogloss:0.27233	eval-mlogloss:0.21425
[53]	train-mlogloss:0.27226	eval-mlogloss:0.21391
[54]	train-mlogloss:0.27216	eval-mlogloss:0.21366
[55]	train-mlogloss:0.27181	eval-mlogloss:0.21311
[56]	train-mlogloss:0.27174	eval-mlogloss:0.21281
[57]	train-mlogloss:0.27160	eval-mlogloss:0.21235
[58]	train-mlogloss:0.27165	eval-mlogloss:0.21236
[59]	train-mlogloss:0.27107	eval-mlogloss:0.21181
[60]	train-mlogloss:0.27097	eval-mlogloss:0.21197
[61]	train-mlogloss:0.27058	eval-mlogloss:0.21159
[62]	train-mlogloss:0.26982	eval-mlogloss:0.21051
[63]	train-mlogloss:0.26982	eval-mlogloss:0.21032
[64]	train-mlogloss:0.26974	eval-mlogloss:0.21033
[65]	train-mlogloss:0.26986	eval-mlogloss:0.21059
[66]	train-mlogloss:0.26975	eval-mlogloss:0.21072
[67]	train-mlogloss:0.26969	eval-mlogloss:0.21086
[68]	train-mlogloss:0.26951	eval-mlogloss:0.21050
[69]	train-mlogloss:0.26918	eval-mlogloss:0.21036
[70]	train-mlogloss:0.26918	eval-mlogloss:0.21029
[71]	train-mlogloss:0.26921	eval-mlogloss:0.21033
[72]	train-mlogloss:0.26921	eval-mlogloss:0.21014
[73]	train-mlogloss:0.26919	eval-mlogloss:0.20992
[74]	train-mlogloss:0.26924	eval-mlogloss:0.21020
[75]	train-mlogloss:0.26930	eval-mlogloss:0.21030
[76]	train-mlogloss:0.26926	eval-mlogloss:0.20986
[77]	train-mlogloss:0.26929	eval-mlogloss:0.21016
[78]	train-mlogloss:0.26923	eval-mlogloss:0.21021
[79]	train-mlogloss:0.26925	eval-mlogloss:0.21035
[80]	train-mlogloss:0.26875	eval-mlogloss:0.21004
[81]	train-mlogloss:0.26875	eval-mlogloss:0.21030
[82]	train-mlogloss:0.26870	eval-mlogloss:0.21026
[83]	train-mlogloss:0.26870	eval-mlogloss:0.21013
[84]	train-mlogloss:0.26870	eval-mlogloss:0.21014
[85]	train-mlogloss:0.26863	eval-mlogloss:0.21000
[86]	train-mlogloss:0.26862	eval-mlogloss:0.21004

[I 2025-09-13 06:38:39,055] Trial 1 finished with value: 1.0 and parameters: {'lambda': 0.07109138125182143, 'alpha': 0.04064625741667164, 'eta': 0.1164408296462487, 'gamma': 6.0857300507270935e-06, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.49773642202748763, 'colsample_bytree': 0.4673146118312575}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.00374	eval-mlogloss:0.99664
[1]	train-mlogloss:0.92054	eval-mlogloss:0.90897
[2]	train-mlogloss:0.84622	eval-mlogloss:0.83027
[3]	train-mlogloss:0.78026	eval-mlogloss:0.76379
[4]	train-mlogloss:0.72201	eval-mlogloss:0.70456
[5]	train-mlogloss:0.66854	eval-mlogloss:0.64718
[6]	train-mlogloss:0.62232	eval-mlogloss:0.59946
[7]	train-mlogloss:0.58012	eval-mlogloss:0.55595
[8]	train-mlogloss:0.54145	eval-mlogloss:0.51401
[9]	train-mlogloss:0.50657	eval-mlogloss:0.47726
[10]	train-mlogloss:0.47408	eval-mlogloss:0.44422
[11]	train-mlogloss:0.44502	eval-mlogloss:0.41333
[12]	train-mlogloss:0.41876	eval-mlogloss:0.38411
[13]	train-mlogloss:0.39430	eval-mlogloss:0.35767
[14]	train-mlogloss:0.37198	eval-mlogloss:0.33427
[15]	train-mlogloss:0.35152	eval-mlogloss:0.31273

[I 2025-09-13 06:38:39,088] Trial 2 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.03801	eval-mlogloss:1.04068
[1]	train-mlogloss:0.96104	eval-mlogloss:0.95980
[2]	train-mlogloss:0.89193	eval-mlogloss:0.88725
[3]	train-mlogloss:0.82948	eval-mlogloss:0.82302
[4]	train-mlogloss:0.77373	eval-mlogloss:0.76417
[5]	train-mlogloss:0.72303	eval-mlogloss:0.71225
[6]	train-mlogloss:0.67743	eval-mlogloss:0.66465
[7]	train-mlogloss:0.63558	eval-mlogloss:0.62018
[8]	train-mlogloss:0.59756	eval-mlogloss:0.57983
[9]	train-mlogloss:0.56241	eval-mlogloss:0.54238
[10]	train-mlogloss:0.53001	eval-mlogloss:0.50849
[11]	train-mlogloss:0.50033	eval-mlogloss:0.47737
[12]	train-mlogloss:0.48321	eval-mlogloss:0.45975
[13]	train-mlogloss:0.45712	eval-mlogloss:0.43108
[14]	train-mlogloss:0.44110	eval-mlogloss:0.41422
[15]	train-mlogloss:0.42110	eval-mlogloss:0.39285
[16]	train-mlogloss:0.40253	eval-mlogloss:0.37353
[17]	train-mlogloss:0.38710	eval-mlogloss:0.35765
[18]	train-mlogloss:0.36826	eval-mlogloss:0.33781
[19]	train-mlogloss:0.35417	eval-mlogloss:0.32272
[20]	train-mlogloss:0.33763	eval-mlogloss:0.30532
[21]	train-mlogloss:0.32232	eval-mlogloss:0.28814
[22]	train-mlogloss:0.31018	eval-mlogloss:0.27474
[23]	train-mlogloss:0.29671	eval-mlogloss:0.26059
[24]	train-mlogloss:0.28428	eval-mlogloss:0.24654
[25]	train-mlogloss:0.27279	eval-mlogloss:0.23350
[26]	train-mlogloss:0.26387	eval-mlogloss:0.22511
[27]	train-mlogloss:0.25384	eval-mlogloss:0.21466
[28]	train-mlogloss:0.24724	eval-mlogloss:0.20767
[29]	train-mlogloss:0.23847	eval-mlogloss:0.19784
[30]	train-mlogloss:0.23073	eval-mlogloss:0.18933
[31]	train-mlogloss:0.22464	eval-mlogloss:0.18358
[32]	train-mlogloss:0.21755	eval-mlogloss:0.17576
[33]	train-mlogloss:0.21402	eval-mlogloss:0.17200
[34]	train-mlogloss:0.20740	eval-mlogloss:0.16515
[35]	train-mlogloss:0.20138	eval-mlogloss:0.15812
[36]	train-mlogloss:0.19677	eval-mlogloss:0.15379
[37]	train-mlogloss:0.19145	eval-mlogloss:0.14846
[38]	train-mlogloss:0.18759	eval-mlogloss:0.14404
[39]	train-mlogloss:0.18402	eval-mlogloss:0.14008
[40]	train-mlogloss:0.18047	eval-mlogloss:0.13659
[41]	train-mlogloss:0.17647	eval-mlogloss:0.13156
[42]	train-mlogloss:0.17416	eval-mlogloss:0.12893
[43]	train-mlogloss:0.17153	eval-mlogloss:0.12662
[44]	train-mlogloss:0.16801	eval-mlogloss:0.12231
[45]	train-mlogloss:0.16682	eval-mlogloss:0.12151
[46]	train-mlogloss:0.16387	eval-mlogloss:0.11754
[47]	train-mlogloss:0.16263	eval-mlogloss:0.11608
[48]	train-mlogloss:0.16117	eval-mlogloss:0.11412
[49]	train-mlogloss:0.15952	eval-mlogloss:0.11182
[50]	train-mlogloss:0.15838	eval-mlogloss:0.11002
[51]	train-mlogloss:0.15733	eval-mlogloss:0.10870
[52]	train-mlogloss:0.15629	eval-mlogloss:0.10707
[53]	train-mlogloss:0.15534	eval-mlogloss:0.10555
[54]	train-mlogloss:0.15493	eval-mlogloss:0.10544
[55]	train-mlogloss:0.15399	eval-mlogloss:0.10393
[56]	train-mlogloss:0.15312	eval-mlogloss:0.10285
[57]	train-mlogloss:0.15231	eval-mlogloss:0.10164
[58]	train-mlogloss:0.15156	eval-mlogloss:0.10043
[59]	train-mlogloss:0.15118	eval-mlogloss:0.10038
[60]	train-mlogloss:0.15046	eval-mlogloss:0.09927
[61]	train-mlogloss:0.14972	eval-mlogloss:0.09847
[62]	train-mlogloss:0.14900	eval-mlogloss:0.09757
[63]	train-mlogloss:0.14841	eval-mlogloss:0.09667
[64]	train-mlogloss:0.14773	eval-mlogloss:0.09594

[I 2025-09-13 06:38:39,224] Trial 3 pruned. Trial was pruned at iteration 64.

[0]	train-mlogloss:0.89595	eval-mlogloss:0.88197

[I 2025-09-13 06:38:39,232] Trial 4 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.96464	eval-mlogloss:0.97156

[I 2025-09-13 06:38:39,240] Trial 5 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.00240	eval-mlogloss:0.99559

[I 2025-09-13 06:38:39,245] Trial 6 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97588	eval-mlogloss:0.97918

[I 2025-09-13 06:38:39,250] Trial 7 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02217	eval-mlogloss:1.02542
[1]	train-mlogloss:0.93776	eval-mlogloss:0.92524
[2]	train-mlogloss:0.84463	eval-mlogloss:0.82754
[3]	train-mlogloss:0.74824	eval-mlogloss:0.72548

[I 2025-09-13 06:38:39,259] Trial 8 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.94907	eval-mlogloss:0.94019

[I 2025-09-13 06:38:39,266] Trial 9 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07769	eval-mlogloss:1.07633
[1]	train-mlogloss:1.05748	eval-mlogloss:1.05556
[2]	train-mlogloss:1.03712	eval-mlogloss:1.03435
[3]	train-mlogloss:1.01724	eval-mlogloss:1.01369
[4]	train-mlogloss:0.99859	eval-mlogloss:0.99465
[5]	train-mlogloss:0.97949	eval-mlogloss:0.97461
[6]	train-mlogloss:0.96132	eval-mlogloss:0.95633
[7]	train-mlogloss:0.94433	eval-mlogloss:0.93898
[8]	train-mlogloss:0.92758	eval-mlogloss:0.92120
[9]	train-mlogloss:0.91107	eval-mlogloss:0.90392
[10]	train-mlogloss:0.89483	eval-mlogloss:0.88796
[11]	train-mlogloss:0.87930	eval-mlogloss:0.87139
[12]	train-mlogloss:0.86432	eval-mlogloss:0.85616
[13]	train-mlogloss:0.84927	eval-mlogloss:0.84049
[14]	train-mlogloss:0.83495	eval-mlogloss:0.82602
[15]	train-mlogloss:0.82062	eval-mlogloss:0.81111
[16]	train-mlogloss:0.80699	eval-mlogloss:0.79659
[17]	train-mlogloss:0.79356	eval-mlogloss:0.78184
[18]	train-mlogloss:0.78098	eval-mlogloss:0.76892
[19]	train-mlogloss:0.76810	eval-mlogloss:0.75522
[20]	train-mlogloss:0.75517	eval-mlogloss:0.74142
[21]	train-mlogloss:0.74323	eval-mlogloss:0.72886
[22]	train-mlogloss:0.73047	eval-mlogloss:0.71529
[23]	train-mlogloss:0.71843	eval-mlogloss:0.70276
[24]	train-mlogloss:0.70673	eval-mlogloss:0.69039
[25]	train-mlogloss:0.69545	eval-mlogloss:0.67832
[26]	train-mlogloss:0.68464	eval-mlogloss:0.66663
[27]	train-mlogloss:0.67373	eval-mlogloss:0.65543
[28]	train-mlogloss:0.66296	eval-mlogloss:0.64407
[29]	train-mlogloss:0.65228	eval-mlogloss:0.63290
[30]	train-mlogloss:0.64173	eval-mlogloss:0.62227
[31]	train-mlogloss:0.63143	eval-mlogloss:0.61142
[32]	train-mlogloss:0.62150	eval-mlogloss:0.60108
[33]	train-mlogloss:0.61261	eval-mlogloss:0.59163
[34]	train-mlogloss:0.60323	eval-mlogloss:0.58199
[35]	train-mlogloss:0.59460	eval-mlogloss:0.57278
[36]	train-mlogloss:0.58538	eval-mlogloss:0.56349
[37]	train-mlogloss:0.57674	eval-mlogloss:0.55453
[38]	train-mlogloss:0.56842	eval-mlogloss:0.54578
[39]	train-mlogloss:0.55951	eval-mlogloss:0.53640
[40]	train-mlogloss:0.55064	eval-mlogloss:0.52845
[41]	train-mlogloss:0.54247	eval-mlogloss:0.51951
[42]	train-mlogloss:0.53465	eval-mlogloss:0.51111
[43]	train-mlogloss:0.52686	eval-mlogloss:0.50285
[44]	train-mlogloss:0.51910	eval-mlogloss:0.49476
[45]	train-mlogloss:0.51114	eval-mlogloss:0.48655
[46]	train-mlogloss:0.50330	eval-mlogloss:0.47829
[47]	train-mlogloss:0.49604	eval-mlogloss:0.47073
[48]	train-mlogloss:0.48864	eval-mlogloss:0.46287
[49]	train-mlogloss:0.48166	eval-mlogloss:0.45536
[50]	train-mlogloss:0.47451	eval-mlogloss:0.44767
[51]	train-mlogloss:0.46764	eval-mlogloss:0.44007
[52]	train-mlogloss:0.46096	eval-mlogloss:0.43269
[53]	train-mlogloss:0.45460	eval-mlogloss:0.42582
[54]	train-mlogloss:0.44799	eval-mlogloss:0.41910
[55]	train-mlogloss:0.44152	eval-mlogloss:0.41224
[56]	train-mlogloss:0.43551	eval-mlogloss:0.40577
[57]	train-mlogloss:0.42953	eval-mlogloss:0.39995
[58]	train-mlogloss:0.42349	eval-mlogloss:0.39343
[59]	train-mlogloss:0.41777	eval-mlogloss:0.38733
[60]	train-mlogloss:0.41213	eval-mlogloss:0.38140
[61]	train-mlogloss:0.40655	eval-mlogloss:0.37604
[62]	train-mlogloss:0.40099	eval-mlogloss:0.37020
[63]	train-mlogloss:0.39548	eval-mlogloss:0.36429
[64]	train-mlogloss:0.39016	eval-mlogloss:0.35862
[65]	train-mlogloss:0.38490	eval-mlogloss:0.35290
[66]	train-mlogloss:0.37959	eval-mlogloss:0.34798
[67]	train-mlogloss:0.37447	eval-mlogloss:0.34240
[68]	train-mlogloss:0.36962	eval-mlogloss:0.33708
[69]	train-mlogloss:0.36485	eval-mlogloss:0.33219
[70]	train-mlogloss:0.35999	eval-mlogloss:0.32715
[71]	train-mlogloss:0.35535	eval-mlogloss:0.32239
[72]	train-mlogloss:0.35088	eval-mlogloss:0.31795
[73]	train-mlogloss:0.34604	eval-mlogloss:0.31298
[74]	train-mlogloss:0.34156	eval-mlogloss:0.30816
[75]	train-mlogloss:0.33717	eval-mlogloss:0.30404
[76]	train-mlogloss:0.33273	eval-mlogloss:0.29952
[77]	train-mlogloss:0.32851	eval-mlogloss:0.29513
[78]	train-mlogloss:0.32438	eval-mlogloss:0.29035
[79]	train-mlogloss:0.32019	eval-mlogloss:0.28604
[80]	train-mlogloss:0.31603	eval-mlogloss:0.28143
[81]	train-mlogloss:0.31193	eval-mlogloss:0.27700
[82]	train-mlogloss:0.30788	eval-mlogloss:0.27269
[83]	train-mlogloss:0.30383	eval-mlogloss:0.26839
[84]	train-mlogloss:0.29984	eval-mlogloss:0.26470
[85]	train-mlogloss:0.29601	eval-mlogloss:0.26066
[86]	train-mlogloss:0.29223	eval-mlogloss:0.25674
[87]	train-mlogloss:0.28849	eval-mlogloss:0.25284
[88]	train-mlogloss:0.28487	eval-mlogloss:0.24928
[89]	train-mlogloss:0.28127	eval-mlogloss:0.24533
[90]	train-mlogloss:0.27784	eval-mlogloss:0.24179
[91]	train-mlogloss:0.27431	eval-mlogloss:0.23835
[92]	train-mlogloss:0.27088	eval-mlogloss:0.23491
[93]	train-mlogloss:0.26768	eval-mlogloss:0.23177
[94]	train-mlogloss:0.26448	eval-mlogloss:0.22840
[95]	train-mlogloss:0.26149	eval-mlogloss:0.22500
[96]	train-mlogloss:0.25835	eval-mlogloss:0.22138
[97]	train-mlogloss:0.25522	eval-mlogloss:0.21800
[98]	train-mlogloss:0.25224	eval-mlogloss:0.21461
[99]	train-mlogloss:0.24934	eval-mlogloss:0.21218
[100]	train-mlogloss:0.24631	eval-mlogloss:0.20925
[101]	train-mlogloss:0.24346	eval-mlogloss:0.20625
[102]	train-mlogloss:0.24057	eval-mlogloss:0.20342
[103]	train-mlogloss:0.23778	eval-mlogloss:0.20050
[104]	train-mlogloss:0.23511	eval-mlogloss:0.19747
[105]	train-mlogloss:0.23270	eval-mlogloss:0.19500
[106]	train-mlogloss:0.22986	eval-mlogloss:0.19263
[107]	train-mlogloss:0.22729	eval-mlogloss:0.18967
[108]	train-mlogloss:0.22476	eval-mlogloss:0.18679
[109]	train-mlogloss:0.22230	eval-mlogloss:0.18410
[110]	train-mlogloss:0.21975	eval-mlogloss:0.18123
[111]	train-mlogloss:0.21732	eval-mlogloss:0.17884
[112]	train-mlogloss:0.21478	eval-mlogloss:0.17634
[113]	train-mlogloss:0.21251	eval-mlogloss:0.17402
[114]	train-mlogloss:0.21024	eval-mlogloss:0.17166
[115]	train-mlogloss:0.20771	eval-mlogloss:0.16964
[116]	train-mlogloss:0.20561	eval-mlogloss:0.16740
[117]	train-mlogloss:0.20342	eval-mlogloss:0.16485
[118]	train-mlogloss:0.20107	eval-mlogloss:0.16278
[119]	train-mlogloss:0.19878	eval-mlogloss:0.16032
[120]	train-mlogloss:0.19651	eval-mlogloss:0.15851
[121]	train-mlogloss:0.19431	eval-mlogloss:0.15603
[122]	train-mlogloss:0.19231	eval-mlogloss:0.15387
[123]	train-mlogloss:0.19042	eval-mlogloss:0.15195
[124]	train-mlogloss:0.18832	eval-mlogloss:0.15021
[125]	train-mlogloss:0.18613	eval-mlogloss:0.14830
[126]	train-mlogloss:0.18418	eval-mlogloss:0.14659
[127]	train-mlogloss:0.18221	eval-mlogloss:0.14499
[128]	train-mlogloss:0.18039	eval-mlogloss:0.14284
[129]	train-mlogloss:0.17842	eval-mlogloss:0.14116
[130]	train-mlogloss:0.17664	eval-mlogloss:0.13952
[131]	train-mlogloss:0.17478	eval-mlogloss:0.13757
[132]	train-mlogloss:0.17294	eval-mlogloss:0.13584
[133]	train-mlogloss:0.17122	eval-mlogloss:0.13420
[134]	train-mlogloss:0.16964	eval-mlogloss:0.13238
[135]	train-mlogloss:0.16815	eval-mlogloss:0.13071
[136]	train-mlogloss:0.16648	eval-mlogloss:0.12901
[137]	train-mlogloss:0.16486	eval-mlogloss:0.12752
[138]	train-mlogloss:0.16327	eval-mlogloss:0.12598
[139]	train-mlogloss:0.16166	eval-mlogloss:0.12431
[140]	train-mlogloss:0.16009	eval-mlogloss:0.12293
[141]	train-mlogloss:0.15862	eval-mlogloss:0.12132
[142]	train-mlogloss:0.15718	eval-mlogloss:0.11966
[143]	train-mlogloss:0.15569	eval-mlogloss:0.11822
[144]	train-mlogloss:0.15431	eval-mlogloss:0.11675
[145]	train-mlogloss:0.15281	eval-mlogloss:0.11515
[146]	train-mlogloss:0.15144	eval-mlogloss:0.11351
[147]	train-mlogloss:0.15009	eval-mlogloss:0.11208
[148]	train-mlogloss:0.14869	eval-mlogloss:0.11070
[149]	train-mlogloss:0.14725	eval-mlogloss:0.10956
[150]	train-mlogloss:0.14609	eval-mlogloss:0.10858
[151]	train-mlogloss:0.14473	eval-mlogloss:0.10728
[152]	train-mlogloss:0.14354	eval-mlogloss:0.10622
[153]	train-mlogloss:0.14234	eval-mlogloss:0.10495
[154]	train-mlogloss:0.14110	eval-mlogloss:0.10368
[155]	train-mlogloss:0.13988	eval-mlogloss:0.10227
[156]	train-mlogloss:0.13870	eval-mlogloss:0.10077
[157]	train-mlogloss:0.13742	eval-mlogloss:0.09939
[158]	train-mlogloss:0.13628	eval-mlogloss:0.09820
[159]	train-mlogloss:0.13520	eval-mlogloss:0.09699
[160]	train-mlogloss:0.13408	eval-mlogloss:0.09573
[161]	train-mlogloss:0.13285	eval-mlogloss:0.09478
[162]	train-mlogloss:0.13184	eval-mlogloss:0.09393
[163]	train-mlogloss:0.13074	eval-mlogloss:0.09325
[164]	train-mlogloss:0.12966	eval-mlogloss:0.09223
[165]	train-mlogloss:0.12843	eval-mlogloss:0.09124
[166]	train-mlogloss:0.12744	eval-mlogloss:0.09016
[167]	train-mlogloss:0.12644	eval-mlogloss:0.08925
[168]	train-mlogloss:0.12549	eval-mlogloss:0.08850
[169]	train-mlogloss:0.12458	eval-mlogloss:0.08736
[170]	train-mlogloss:0.12366	eval-mlogloss:0.08638
[171]	train-mlogloss:0.12282	eval-mlogloss:0.08539
[172]	train-mlogloss:0.12200	eval-mlogloss:0.08459
[173]	train-mlogloss:0.12113	eval-mlogloss:0.08350
[174]	train-mlogloss:0.12031	eval-mlogloss:0.08261
[175]	train-mlogloss:0.11958	eval-mlogloss:0.08215
[176]	train-mlogloss:0.11868	eval-mlogloss:0.08121
[177]	train-mlogloss:0.11782	eval-mlogloss:0.08035
[178]	train-mlogloss:0.11698	eval-mlogloss:0.07963
[179]	train-mlogloss:0.11609	eval-mlogloss:0.07898
[180]	train-mlogloss:0.11539	eval-mlogloss:0.07811
[181]	train-mlogloss:0.11463	eval-mlogloss:0.07711
[182]	train-mlogloss:0.11376	eval-mlogloss:0.07609
[183]	train-mlogloss:0.11303	eval-mlogloss:0.07507
[184]	train-mlogloss:0.11223	eval-mlogloss:0.07436
[185]	train-mlogloss:0.11157	eval-mlogloss:0.07358
[186]	train-mlogloss:0.11080	eval-mlogloss:0.07269
[187]	train-mlogloss:0.11013	eval-mlogloss:0.07210
[188]	train-mlogloss:0.10944	eval-mlogloss:0.07127
[189]	train-mlogloss:0.10870	eval-mlogloss:0.07066
[190]	train-mlogloss:0.10792	eval-mlogloss:0.07003
[191]	train-mlogloss:0.10742	eval-mlogloss:0.06964
[192]	train-mlogloss:0.10677	eval-mlogloss:0.06885
[193]	train-mlogloss:0.10606	eval-mlogloss:0.06823
[194]	train-mlogloss:0.10530	eval-mlogloss:0.06742
[195]	train-mlogloss:0.10475	eval-mlogloss:0.06698
[196]	train-mlogloss:0.10411	eval-mlogloss:0.06648
[197]	train-mlogloss:0.10355	eval-mlogloss:0.06558
[198]	train-mlogloss:0.10296	eval-mlogloss:0.06481
[199]	train-mlogloss:0.10236	eval-mlogloss:0.06433
[200]	train-mlogloss:0.10167	eval-mlogloss:0.06355
[201]	train-mlogloss:0.10110	eval-mlogloss:0.06265
[202]	train-mlogloss:0.10041	eval-mlogloss:0.06185
[203]	train-mlogloss:0.09998	eval-mlogloss:0.06124
[204]	train-mlogloss:0.09945	eval-mlogloss:0.06061
[205]	train-mlogloss:0.09897	eval-mlogloss:0.06020
[206]	train-mlogloss:0.09850	eval-mlogloss:0.05969
[207]	train-mlogloss:0.09813	eval-mlogloss:0.05924
[208]	train-mlogloss:0.09785	eval-mlogloss:0.05891
[209]	train-mlogloss:0.09730	eval-mlogloss:0.05822
[210]	train-mlogloss:0.09719	eval-mlogloss:0.05807
[211]	train-mlogloss:0.09667	eval-mlogloss:0.05773
[212]	train-mlogloss:0.09622	eval-mlogloss:0.05715
[213]	train-mlogloss:0.09582	eval-mlogloss:0.05655
[214]	train-mlogloss:0.09556	eval-mlogloss:0.05637
[215]	train-mlogloss:0.09518	eval-mlogloss:0.05599
[216]	train-mlogloss:0.09465	eval-mlogloss:0.05575
[217]	train-mlogloss:0.09432	eval-mlogloss:0.05540
[218]	train-mlogloss:0.09414	eval-mlogloss:0.05529
[219]	train-mlogloss:0.09380	eval-mlogloss:0.05503
[220]	train-mlogloss:0.09352	eval-mlogloss:0.05497
[221]	train-mlogloss:0.09323	eval-mlogloss:0.05489
[222]	train-mlogloss:0.09277	eval-mlogloss:0.05430
[223]	train-mlogloss:0.09265	eval-mlogloss:0.05399
[224]	train-mlogloss:0.09237	eval-mlogloss:0.05369
[225]	train-mlogloss:0.09220	eval-mlogloss:0.05345
[226]	train-mlogloss:0.09198	eval-mlogloss:0.05323
[227]	train-mlogloss:0.09156	eval-mlogloss:0.05279
[228]	train-mlogloss:0.09129	eval-mlogloss:0.05256
[229]	train-mlogloss:0.09096	eval-mlogloss:0.05236
[230]	train-mlogloss:0.09072	eval-mlogloss:0.05211
[231]	train-mlogloss:0.09065	eval-mlogloss:0.05204
[232]	train-mlogloss:0.09054	eval-mlogloss:0.05185
[233]	train-mlogloss:0.09029	eval-mlogloss:0.05152
[234]	train-mlogloss:0.09004	eval-mlogloss:0.05119
[235]	train-mlogloss:0.08978	eval-mlogloss:0.05085
[236]	train-mlogloss:0.08962	eval-mlogloss:0.05077
[237]	train-mlogloss:0.08954	eval-mlogloss:0.05072
[238]	train-mlogloss:0.08929	eval-mlogloss:0.05049
[239]	train-mlogloss:0.08907	eval-mlogloss:0.05030
[240]	train-mlogloss:0.08897	eval-mlogloss:0.05025
[241]	train-mlogloss:0.08872	eval-mlogloss:0.05013
[242]	train-mlogloss:0.08861	eval-mlogloss:0.05021
[243]	train-mlogloss:0.08840	eval-mlogloss:0.05005
[244]	train-mlogloss:0.08832	eval-mlogloss:0.05011
[245]	train-mlogloss:0.08820	eval-mlogloss:0.05002
[246]	train-mlogloss:0.08798	eval-mlogloss:0.04989
[247]	train-mlogloss:0.08779	eval-mlogloss:0.04973
[248]	train-mlogloss:0.08772	eval-mlogloss:0.04966
[249]	train-mlogloss:0.08759	eval-mlogloss:0.04943
[250]	train-mlogloss:0.08739	eval-mlogloss:0.04912
[251]	train-mlogloss:0.08725	eval-mlogloss:0.04884
[252]	train-mlogloss:0.08684	eval-mlogloss:0.04832
[253]	train-mlogloss:0.08674	eval-mlogloss:0.04812
[254]	train-mlogloss:0.08648	eval-mlogloss:0.04804
[255]	train-mlogloss:0.08628	eval-mlogloss:0.04785
[256]	train-mlogloss:0.08622	eval-mlogloss:0.04786
[257]	train-mlogloss:0.08601	eval-mlogloss:0.04751
[258]	train-mlogloss:0.08590	eval-mlogloss:0.04736
[259]	train-mlogloss:0.08579	eval-mlogloss:0.04722
[260]	train-mlogloss:0.08559	eval-mlogloss:0.04721
[261]	train-mlogloss:0.08548	eval-mlogloss:0.04699
[262]	train-mlogloss:0.08539	eval-mlogloss:0.04683
[263]	train-mlogloss:0.08519	eval-mlogloss:0.04651
[264]	train-mlogloss:0.08502	eval-mlogloss:0.04645
[265]	train-mlogloss:0.08486	eval-mlogloss:0.04635
[266]	train-mlogloss:0.08477	eval-mlogloss:0.04626
[267]	train-mlogloss:0.08449	eval-mlogloss:0.04624
[268]	train-mlogloss:0.08437	eval-mlogloss:0.04615
[269]	train-mlogloss:0.08425	eval-mlogloss:0.04600
[270]	train-mlogloss:0.08403	eval-mlogloss:0.04583
[271]	train-mlogloss:0.08392	eval-mlogloss:0.04574
[272]	train-mlogloss:0.08379	eval-mlogloss:0.04557
[273]	train-mlogloss:0.08371	eval-mlogloss:0.04546
[274]	train-mlogloss:0.08358	eval-mlogloss:0.04516
[275]	train-mlogloss:0.08332	eval-mlogloss:0.04518
[276]	train-mlogloss:0.08323	eval-mlogloss:0.04517
[277]	train-mlogloss:0.08303	eval-mlogloss:0.04491
[278]	train-mlogloss:0.08284	eval-mlogloss:0.04478
[279]	train-mlogloss:0.08274	eval-mlogloss:0.04459
[280]	train-mlogloss:0.08264	eval-mlogloss:0.04465
[281]	train-mlogloss:0.08254	eval-mlogloss:0.04457
[282]	train-mlogloss:0.08235	eval-mlogloss:0.04455
[283]	train-mlogloss:0.08223	eval-mlogloss:0.04452
[284]	train-mlogloss:0.08216	eval-mlogloss:0.04466
[285]	train-mlogloss:0.08211	eval-mlogloss:0.04463
[286]	train-mlogloss:0.08202	eval-mlogloss:0.04450
[287]	train-mlogloss:0.08187	eval-mlogloss:0.04444
[288]	train-mlogloss:0.08174	eval-mlogloss:0.04431
[289]	train-mlogloss:0.08157	eval-mlogloss:0.04416
[290]	train-mlogloss:0.08142	eval-mlogloss:0.04409
[291]	train-mlogloss:0.08131	eval-mlogloss:0.04379
[292]	train-mlogloss:0.08117	eval-mlogloss:0.04363
[293]	train-mlogloss:0.08111	eval-mlogloss:0.04360
[294]	train-mlogloss:0.08099	eval-mlogloss:0.04359
[295]	train-mlogloss:0.08090	eval-mlogloss:0.04350
[296]	train-mlogloss:0.08085	eval-mlogloss:0.04347
[297]	train-mlogloss:0.08073	eval-mlogloss:0.04315
[298]	train-mlogloss:0.08058	eval-mlogloss:0.04295
[299]	train-mlogloss:0.08048	eval-mlogloss:0.04278

[I 2025-09-13 06:38:40,084] Trial 10 finished with value: 1.0 and parameters: {'lambda': 1.3618994585483952e-08, 'alpha': 3.364343012835247e-06, 'eta': 0.015754805861356108, 'gamma': 0.0025117682177764607, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6778442249296561, 'colsample_bytree': 0.9712259927803347}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.98629	eval-mlogloss:1.00132

[I 2025-09-13 06:38:40,109] Trial 11 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.96745	eval-mlogloss:0.96333

[I 2025-09-13 06:38:40,130] Trial 12 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08194	eval-mlogloss:1.08361
[1]	train-mlogloss:1.06250	eval-mlogloss:1.06374
[2]	train-mlogloss:1.04316	eval-mlogloss:1.04330
[3]	train-mlogloss:1.02403	eval-mlogloss:1.02391
[4]	train-mlogloss:1.00566	eval-mlogloss:1.00438
[5]	train-mlogloss:0.98723	eval-mlogloss:0.98481
[6]	train-mlogloss:0.96984	eval-mlogloss:0.96800
[7]	train-mlogloss:0.95331	eval-mlogloss:0.95161
[8]	train-mlogloss:0.93686	eval-mlogloss:0.93411
[9]	train-mlogloss:0.92050	eval-mlogloss:0.91796
[10]	train-mlogloss:0.90486	eval-mlogloss:0.90284
[11]	train-mlogloss:0.88923	eval-mlogloss:0.88717
[12]	train-mlogloss:0.87729	eval-mlogloss:0.87693
[13]	train-mlogloss:0.86256	eval-mlogloss:0.86196
[14]	train-mlogloss:0.85068	eval-mlogloss:0.85104
[15]	train-mlogloss:0.83689	eval-mlogloss:0.83635
[16]	train-mlogloss:0.82355	eval-mlogloss:0.82335
[17]	train-mlogloss:0.81148	eval-mlogloss:0.81217
[18]	train-mlogloss:0.79820	eval-mlogloss:0.79860
[19]	train-mlogloss:0.78665	eval-mlogloss:0.78781
[20]	train-mlogloss:0.77356	eval-mlogloss:0.77509
[21]	train-mlogloss:0.76089	eval-mlogloss:0.76136
[22]	train-mlogloss:0.74880	eval-mlogloss:0.74957
[23]	train-mlogloss:0.73669	eval-mlogloss:0.73655
[24]	train-mlogloss:0.72504	eval-mlogloss:0.72460
[25]	train-mlogloss:0.71385	eval-mlogloss:0.71219
[26]	train-mlogloss:0.70380	eval-mlogloss:0.70386
[27]	train-mlogloss:0.69268	eval-mlogloss:0.69277
[28]	train-mlogloss:0.68270	eval-mlogloss:0.68400
[29]	train-mlogloss:0.67179	eval-mlogloss:0.67267
[30]	train-mlogloss:0.66141	eval-mlogloss:0.66223
[31]	train-mlogloss:0.65229	eval-mlogloss:0.65404
[32]	train-mlogloss:0.64228	eval-mlogloss:0.64379
[33]	train-mlogloss:0.63481	eval-mlogloss:0.63739
[34]	train-mlogloss:0.62497	eval-mlogloss:0.62712
[35]	train-mlogloss:0.61583	eval-mlogloss:0.61706
[36]	train-mlogloss:0.60755	eval-mlogloss:0.60979
[37]	train-mlogloss:0.59825	eval-mlogloss:0.60025
[38]	train-mlogloss:0.58948	eval-mlogloss:0.59251
[39]	train-mlogloss:0.58068	eval-mlogloss:0.58348
[40]	train-mlogloss:0.57338	eval-mlogloss:0.57697
[41]	train-mlogloss:0.56515	eval-mlogloss:0.56812
[42]	train-mlogloss:0.55838	eval-mlogloss:0.56156
[43]	train-mlogloss:0.55087	eval-mlogloss:0.55507
[44]	train-mlogloss:0.54283	eval-mlogloss:0.54661
[45]	train-mlogloss:0.53572	eval-mlogloss:0.54041
[46]	train-mlogloss:0.52802	eval-mlogloss:0.53250
[47]	train-mlogloss:0.52024	eval-mlogloss:0.52471
[48]	train-mlogloss:0.51265	eval-mlogloss:0.51739
[49]	train-mlogloss:0.50533	eval-mlogloss:0.50995
[50]	train-mlogloss:0.49806	eval-mlogloss:0.50247
[51]	train-mlogloss:0.49115	eval-mlogloss:0.49516
[52]	train-mlogloss:0.48430	eval-mlogloss:0.48850
[53]	train-mlogloss:0.47760	eval-mlogloss:0.48110
[54]	train-mlogloss:0.47143	eval-mlogloss:0.47525
[55]	train-mlogloss:0.46470	eval-mlogloss:0.46789
[56]	train-mlogloss:0.45843	eval-mlogloss:0.46139
[57]	train-mlogloss:0.45220	eval-mlogloss:0.45459
[58]	train-mlogloss:0.44596	eval-mlogloss:0.44772
[59]	train-mlogloss:0.44040	eval-mlogloss:0.44215
[60]	train-mlogloss:0.43444	eval-mlogloss:0.43544
[61]	train-mlogloss:0.42919	eval-mlogloss:0.43060
[62]	train-mlogloss:0.42322	eval-mlogloss:0.42506
[63]	train-mlogloss:0.41823	eval-mlogloss:0.42023
[64]	train-mlogloss:0.41331	eval-mlogloss:0.41664
[65]	train-mlogloss:0.40776	eval-mlogloss:0.41115
[66]	train-mlogloss:0.40260	eval-mlogloss:0.40553
[67]	train-mlogloss:0.39701	eval-mlogloss:0.39977
[68]	train-mlogloss:0.39252	eval-mlogloss:0.39529
[69]	train-mlogloss:0.38747	eval-mlogloss:0.38977
[70]	train-mlogloss:0.38316	eval-mlogloss:0.38576
[71]	train-mlogloss:0.37816	eval-mlogloss:0.38021
[72]	train-mlogloss:0.37301	eval-mlogloss:0.37454
[73]	train-mlogloss:0.36800	eval-mlogloss:0.36898
[74]	train-mlogloss:0.36308	eval-mlogloss:0.36445
[75]	train-mlogloss:0.35846	eval-mlogloss:0.35991
[76]	train-mlogloss:0.35372	eval-mlogloss:0.35585
[77]	train-mlogloss:0.34973	eval-mlogloss:0.35217
[78]	train-mlogloss:0.34520	eval-mlogloss:0.34720
[79]	train-mlogloss:0.34058	eval-mlogloss:0.34243
[80]	train-mlogloss:0.33623	eval-mlogloss:0.33851
[81]	train-mlogloss:0.33184	eval-mlogloss:0.33376
[82]	train-mlogloss:0.32766	eval-mlogloss:0.32962
[83]	train-mlogloss:0.32421	eval-mlogloss:0.32623
[84]	train-mlogloss:0.31993	eval-mlogloss:0.32209
[85]	train-mlogloss:0.31648	eval-mlogloss:0.31876
[86]	train-mlogloss:0.31234	eval-mlogloss:0.31443
[87]	train-mlogloss:0.30842	eval-mlogloss:0.31065
[88]	train-mlogloss:0.30461	eval-mlogloss:0.30616
[89]	train-mlogloss:0.30070	eval-mlogloss:0.30180
[90]	train-mlogloss:0.29682	eval-mlogloss:0.29761
[91]	train-mlogloss:0.29324	eval-mlogloss:0.29405
[92]	train-mlogloss:0.28945	eval-mlogloss:0.29027
[93]	train-mlogloss:0.28706	eval-mlogloss:0.28822
[94]	train-mlogloss:0.28347	eval-mlogloss:0.28421
[95]	train-mlogloss:0.28015	eval-mlogloss:0.28040
[96]	train-mlogloss:0.27675	eval-mlogloss:0.27736
[97]	train-mlogloss:0.27299	eval-mlogloss:0.27340
[98]	train-mlogloss:0.26964	eval-mlogloss:0.26982
[99]	train-mlogloss:0.26650	eval-mlogloss:0.26714
[100]	train-mlogloss:0.26322	eval-mlogloss:0.26349
[101]	train-mlogloss:0.26001	eval-mlogloss:0.25991
[102]	train-mlogloss:0.25679	eval-mlogloss:0.25637
[103]	train-mlogloss:0.25358	eval-mlogloss:0.25291
[104]	train-mlogloss:0.25060	eval-mlogloss:0.24934
[105]	train-mlogloss:0.24764	eval-mlogloss:0.24633
[106]	train-mlogloss:0.24487	eval-mlogloss:0.24384
[107]	train-mlogloss:0.24205	eval-mlogloss:0.24045
[108]	train-mlogloss:0.23979	eval-mlogloss:0.23790
[109]	train-mlogloss:0.23699	eval-mlogloss:0.23479
[110]	train-mlogloss:0.23414	eval-mlogloss:0.23130
[111]	train-mlogloss:0.23141	eval-mlogloss:0.22829
[112]	train-mlogloss:0.22870	eval-mlogloss:0.22520
[113]	train-mlogloss:0.22611	eval-mlogloss:0.22212
[114]	train-mlogloss:0.22389	eval-mlogloss:0.22020
[115]	train-mlogloss:0.22128	eval-mlogloss:0.21766
[116]	train-mlogloss:0.21862	eval-mlogloss:0.21455
[117]	train-mlogloss:0.21614	eval-mlogloss:0.21149
[118]	train-mlogloss:0.21361	eval-mlogloss:0.20949
[119]	train-mlogloss:0.21141	eval-mlogloss:0.20722
[120]	train-mlogloss:0.20897	eval-mlogloss:0.20458
[121]	train-mlogloss:0.20654	eval-mlogloss:0.20184
[122]	train-mlogloss:0.20426	eval-mlogloss:0.19917
[123]	train-mlogloss:0.20198	eval-mlogloss:0.19649
[124]	train-mlogloss:0.19973	eval-mlogloss:0.19422
[125]	train-mlogloss:0.19747	eval-mlogloss:0.19162
[126]	train-mlogloss:0.19551	eval-mlogloss:0.18977
[127]	train-mlogloss:0.19377	eval-mlogloss:0.18803
[128]	train-mlogloss:0.19151	eval-mlogloss:0.18567
[129]	train-mlogloss:0.18969	eval-mlogloss:0.18402
[130]	train-mlogloss:0.18785	eval-mlogloss:0.18220
[131]	train-mlogloss:0.18574	eval-mlogloss:0.17968
[132]	train-mlogloss:0.18370	eval-mlogloss:0.17740
[133]	train-mlogloss:0.18189	eval-mlogloss:0.17527
[134]	train-mlogloss:0.18021	eval-mlogloss:0.17335
[135]	train-mlogloss:0.17833	eval-mlogloss:0.17136
[136]	train-mlogloss:0.17630	eval-mlogloss:0.16907
[137]	train-mlogloss:0.17421	eval-mlogloss:0.16688
[138]	train-mlogloss:0.17238	eval-mlogloss:0.16484
[139]	train-mlogloss:0.17078	eval-mlogloss:0.16321
[140]	train-mlogloss:0.16900	eval-mlogloss:0.16131
[141]	train-mlogloss:0.16746	eval-mlogloss:0.15972
[142]	train-mlogloss:0.16595	eval-mlogloss:0.15824
[143]	train-mlogloss:0.16410	eval-mlogloss:0.15610
[144]	train-mlogloss:0.16220	eval-mlogloss:0.15416
[145]	train-mlogloss:0.16045	eval-mlogloss:0.15217
[146]	train-mlogloss:0.15882	eval-mlogloss:0.15034
[147]	train-mlogloss:0.15713	eval-mlogloss:0.14844
[148]	train-mlogloss:0.15555	eval-mlogloss:0.14649
[149]	train-mlogloss:0.15413	eval-mlogloss:0.14522
[150]	train-mlogloss:0.15241	eval-mlogloss:0.14371
[151]	train-mlogloss:0.15067	eval-mlogloss:0.14184
[152]	train-mlogloss:0.14916	eval-mlogloss:0.14008
[153]	train-mlogloss:0.14767	eval-mlogloss:0.13837
[154]	train-mlogloss:0.14613	eval-mlogloss:0.13664
[155]	train-mlogloss:0.14460	eval-mlogloss:0.13483
[156]	train-mlogloss:0.14318	eval-mlogloss:0.13312
[157]	train-mlogloss:0.14171	eval-mlogloss:0.13136
[158]	train-mlogloss:0.14027	eval-mlogloss:0.12959
[159]	train-mlogloss:0.13898	eval-mlogloss:0.12828
[160]	train-mlogloss:0.13759	eval-mlogloss:0.12704
[161]	train-mlogloss:0.13609	eval-mlogloss:0.12568
[162]	train-mlogloss:0.13481	eval-mlogloss:0.12443
[163]	train-mlogloss:0.13357	eval-mlogloss:0.12323
[164]	train-mlogloss:0.13259	eval-mlogloss:0.12226
[165]	train-mlogloss:0.13146	eval-mlogloss:0.12081
[166]	train-mlogloss:0.13012	eval-mlogloss:0.11923
[167]	train-mlogloss:0.12886	eval-mlogloss:0.11754
[168]	train-mlogloss:0.12775	eval-mlogloss:0.11679
[169]	train-mlogloss:0.12658	eval-mlogloss:0.11561
[170]	train-mlogloss:0.12558	eval-mlogloss:0.11446
[171]	train-mlogloss:0.12431	eval-mlogloss:0.11328
[172]	train-mlogloss:0.12332	eval-mlogloss:0.11260
[173]	train-mlogloss:0.12215	eval-mlogloss:0.11130
[174]	train-mlogloss:0.12115	eval-mlogloss:0.11025
[175]	train-mlogloss:0.11994	eval-mlogloss:0.10899
[176]	train-mlogloss:0.11883	eval-mlogloss:0.10763
[177]	train-mlogloss:0.11787	eval-mlogloss:0.10687
[178]	train-mlogloss:0.11675	eval-mlogloss:0.10576
[179]	train-mlogloss:0.11581	eval-mlogloss:0.10495
[180]	train-mlogloss:0.11474	eval-mlogloss:0.10373
[181]	train-mlogloss:0.11374	eval-mlogloss:0.10241
[182]	train-mlogloss:0.11295	eval-mlogloss:0.10149
[183]	train-mlogloss:0.11200	eval-mlogloss:0.10034
[184]	train-mlogloss:0.11091	eval-mlogloss:0.09941
[185]	train-mlogloss:0.10993	eval-mlogloss:0.09808
[186]	train-mlogloss:0.10905	eval-mlogloss:0.09747
[187]	train-mlogloss:0.10820	eval-mlogloss:0.09644
[188]	train-mlogloss:0.10733	eval-mlogloss:0.09541
[189]	train-mlogloss:0.10623	eval-mlogloss:0.09461
[190]	train-mlogloss:0.10526	eval-mlogloss:0.09351
[191]	train-mlogloss:0.10441	eval-mlogloss:0.09269
[192]	train-mlogloss:0.10337	eval-mlogloss:0.09188
[193]	train-mlogloss:0.10256	eval-mlogloss:0.09096
[194]	train-mlogloss:0.10179	eval-mlogloss:0.09021
[195]	train-mlogloss:0.10093	eval-mlogloss:0.08915
[196]	train-mlogloss:0.10015	eval-mlogloss:0.08864
[197]	train-mlogloss:0.09931	eval-mlogloss:0.08753
[198]	train-mlogloss:0.09852	eval-mlogloss:0.08645
[199]	train-mlogloss:0.09767	eval-mlogloss:0.08550
[200]	train-mlogloss:0.09668	eval-mlogloss:0.08445
[201]	train-mlogloss:0.09609	eval-mlogloss:0.08368
[202]	train-mlogloss:0.09542	eval-mlogloss:0.08337
[203]	train-mlogloss:0.09455	eval-mlogloss:0.08283
[204]	train-mlogloss:0.09391	eval-mlogloss:0.08219
[205]	train-mlogloss:0.09323	eval-mlogloss:0.08155
[206]	train-mlogloss:0.09253	eval-mlogloss:0.08067
[207]	train-mlogloss:0.09179	eval-mlogloss:0.07994
[208]	train-mlogloss:0.09101	eval-mlogloss:0.07927
[209]	train-mlogloss:0.09023	eval-mlogloss:0.07853
[210]	train-mlogloss:0.08965	eval-mlogloss:0.07794
[211]	train-mlogloss:0.08919	eval-mlogloss:0.07767
[212]	train-mlogloss:0.08843	eval-mlogloss:0.07702
[213]	train-mlogloss:0.08778	eval-mlogloss:0.07625
[214]	train-mlogloss:0.08705	eval-mlogloss:0.07560
[215]	train-mlogloss:0.08634	eval-mlogloss:0.07470
[216]	train-mlogloss:0.08559	eval-mlogloss:0.07383
[217]	train-mlogloss:0.08488	eval-mlogloss:0.07290
[218]	train-mlogloss:0.08443	eval-mlogloss:0.07243
[219]	train-mlogloss:0.08365	eval-mlogloss:0.07181
[220]	train-mlogloss:0.08315	eval-mlogloss:0.07137
[221]	train-mlogloss:0.08266	eval-mlogloss:0.07092
[222]	train-mlogloss:0.08198	eval-mlogloss:0.07039
[223]	train-mlogloss:0.08152	eval-mlogloss:0.06989
[224]	train-mlogloss:0.08092	eval-mlogloss:0.06949
[225]	train-mlogloss:0.08035	eval-mlogloss:0.06898
[226]	train-mlogloss:0.07974	eval-mlogloss:0.06833
[227]	train-mlogloss:0.07915	eval-mlogloss:0.06777
[228]	train-mlogloss:0.07856	eval-mlogloss:0.06717
[229]	train-mlogloss:0.07801	eval-mlogloss:0.06658
[230]	train-mlogloss:0.07751	eval-mlogloss:0.06587
[231]	train-mlogloss:0.07704	eval-mlogloss:0.06528
[232]	train-mlogloss:0.07663	eval-mlogloss:0.06487
[233]	train-mlogloss:0.07618	eval-mlogloss:0.06465
[234]	train-mlogloss:0.07574	eval-mlogloss:0.06409
[235]	train-mlogloss:0.07531	eval-mlogloss:0.06351
[236]	train-mlogloss:0.07479	eval-mlogloss:0.06295
[237]	train-mlogloss:0.07419	eval-mlogloss:0.06229
[238]	train-mlogloss:0.07377	eval-mlogloss:0.06175
[239]	train-mlogloss:0.07338	eval-mlogloss:0.06124
[240]	train-mlogloss:0.07292	eval-mlogloss:0.06068
[241]	train-mlogloss:0.07257	eval-mlogloss:0.06057
[242]	train-mlogloss:0.07217	eval-mlogloss:0.06017
[243]	train-mlogloss:0.07184	eval-mlogloss:0.05986
[244]	train-mlogloss:0.07128	eval-mlogloss:0.05937
[245]	train-mlogloss:0.07079	eval-mlogloss:0.05877
[246]	train-mlogloss:0.07050	eval-mlogloss:0.05848
[247]	train-mlogloss:0.07014	eval-mlogloss:0.05812
[248]	train-mlogloss:0.06972	eval-mlogloss:0.05762
[249]	train-mlogloss:0.06933	eval-mlogloss:0.05708
[250]	train-mlogloss:0.06884	eval-mlogloss:0.05641
[251]	train-mlogloss:0.06859	eval-mlogloss:0.05609
[252]	train-mlogloss:0.06817	eval-mlogloss:0.05558
[253]	train-mlogloss:0.06780	eval-mlogloss:0.05513
[254]	train-mlogloss:0.06742	eval-mlogloss:0.05474
[255]	train-mlogloss:0.06719	eval-mlogloss:0.05449
[256]	train-mlogloss:0.06688	eval-mlogloss:0.05412
[257]	train-mlogloss:0.06644	eval-mlogloss:0.05381
[258]	train-mlogloss:0.06614	eval-mlogloss:0.05352
[259]	train-mlogloss:0.06587	eval-mlogloss:0.05332
[260]	train-mlogloss:0.06540	eval-mlogloss:0.05309
[261]	train-mlogloss:0.06513	eval-mlogloss:0.05283
[262]	train-mlogloss:0.06476	eval-mlogloss:0.05240
[263]	train-mlogloss:0.06445	eval-mlogloss:0.05214
[264]	train-mlogloss:0.06420	eval-mlogloss:0.05182
[265]	train-mlogloss:0.06396	eval-mlogloss:0.05155
[266]	train-mlogloss:0.06362	eval-mlogloss:0.05124
[267]	train-mlogloss:0.06332	eval-mlogloss:0.05116
[268]	train-mlogloss:0.06303	eval-mlogloss:0.05067
[269]	train-mlogloss:0.06263	eval-mlogloss:0.05028
[270]	train-mlogloss:0.06229	eval-mlogloss:0.05013
[271]	train-mlogloss:0.06197	eval-mlogloss:0.04985
[272]	train-mlogloss:0.06162	eval-mlogloss:0.04940
[273]	train-mlogloss:0.06127	eval-mlogloss:0.04901
[274]	train-mlogloss:0.06101	eval-mlogloss:0.04863
[275]	train-mlogloss:0.06064	eval-mlogloss:0.04825
[276]	train-mlogloss:0.06034	eval-mlogloss:0.04793
[277]	train-mlogloss:0.06004	eval-mlogloss:0.04776
[278]	train-mlogloss:0.05977	eval-mlogloss:0.04754
[279]	train-mlogloss:0.05943	eval-mlogloss:0.04695
[280]	train-mlogloss:0.05915	eval-mlogloss:0.04650
[281]	train-mlogloss:0.05883	eval-mlogloss:0.04624
[282]	train-mlogloss:0.05862	eval-mlogloss:0.04607
[283]	train-mlogloss:0.05845	eval-mlogloss:0.04604
[284]	train-mlogloss:0.05820	eval-mlogloss:0.04581
[285]	train-mlogloss:0.05798	eval-mlogloss:0.04573
[286]	train-mlogloss:0.05774	eval-mlogloss:0.04538
[287]	train-mlogloss:0.05744	eval-mlogloss:0.04501
[288]	train-mlogloss:0.05712	eval-mlogloss:0.04452
[289]	train-mlogloss:0.05694	eval-mlogloss:0.04443
[290]	train-mlogloss:0.05665	eval-mlogloss:0.04417
[291]	train-mlogloss:0.05639	eval-mlogloss:0.04401
[292]	train-mlogloss:0.05617	eval-mlogloss:0.04381
[293]	train-mlogloss:0.05591	eval-mlogloss:0.04352
[294]	train-mlogloss:0.05569	eval-mlogloss:0.04331
[295]	train-mlogloss:0.05551	eval-mlogloss:0.04306
[296]	train-mlogloss:0.05534	eval-mlogloss:0.04289
[297]	train-mlogloss:0.05514	eval-mlogloss:0.04258
[298]	train-mlogloss:0.05496	eval-mlogloss:0.04225
[299]	train-mlogloss:0.05469	eval-mlogloss:0.04173

[I 2025-09-13 06:38:40,987] Trial 13 finished with value: 1.0 and parameters: {'lambda': 0.003796565729423255, 'alpha': 0.0221607810699946, 'eta': 0.014979756886058862, 'gamma': 0.0016546170598322543, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.7551806812473738, 'colsample_bytree': 0.531426630338508}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.92918	eval-mlogloss:0.93827
[1]	train-mlogloss:0.74131	eval-mlogloss:0.73360

[I 2025-09-13 06:38:41,014] Trial 14 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03691	eval-mlogloss:1.03886

[I 2025-09-13 06:38:41,034] Trial 15 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97694	eval-mlogloss:0.96463
[1]	train-mlogloss:0.81738	eval-mlogloss:0.79393

[I 2025-09-13 06:38:41,059] Trial 16 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.04311	eval-mlogloss:1.03928
[1]	train-mlogloss:0.99456	eval-mlogloss:0.98968
[2]	train-mlogloss:0.94662	eval-mlogloss:0.93848
[3]	train-mlogloss:0.89860	eval-mlogloss:0.88825
[4]	train-mlogloss:0.85623	eval-mlogloss:0.84357

[I 2025-09-13 06:38:41,109] Trial 17 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.84223	eval-mlogloss:0.81951

[I 2025-09-13 06:38:41,144] Trial 18 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02112	eval-mlogloss:1.02586
[1]	train-mlogloss:0.92497	eval-mlogloss:0.92121

[I 2025-09-13 06:38:41,160] Trial 19 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.91830	eval-mlogloss:0.91427

[I 2025-09-13 06:38:41,182] Trial 20 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05521	eval-mlogloss:1.05197
[1]	train-mlogloss:1.01396	eval-mlogloss:1.00985
[2]	train-mlogloss:0.97399	eval-mlogloss:0.96774
[3]	train-mlogloss:0.93520	eval-mlogloss:0.92777
[4]	train-mlogloss:0.90025	eval-mlogloss:0.89073

[I 2025-09-13 06:38:41,210] Trial 21 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.02539	eval-mlogloss:1.02058
[1]	train-mlogloss:0.95968	eval-mlogloss:0.95344

[I 2025-09-13 06:38:41,228] Trial 22 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07241	eval-mlogloss:1.07019
[1]	train-mlogloss:1.04667	eval-mlogloss:1.04423
[2]	train-mlogloss:1.02145	eval-mlogloss:1.01777
[3]	train-mlogloss:0.99658	eval-mlogloss:0.99222
[4]	train-mlogloss:0.97344	eval-mlogloss:0.96774

[I 2025-09-13 06:38:41,263] Trial 23 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.78604	eval-mlogloss:0.76586
[1]	train-mlogloss:0.59133	eval-mlogloss:0.55858

[I 2025-09-13 06:38:41,281] Trial 24 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02501	eval-mlogloss:1.02152

[I 2025-09-13 06:38:41,304] Trial 25 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.96320	eval-mlogloss:0.95332
[1]	train-mlogloss:0.83054	eval-mlogloss:0.80448

[I 2025-09-13 06:38:41,323] Trial 26 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.94395	eval-mlogloss:0.93310
[1]	train-mlogloss:0.84425	eval-mlogloss:0.82153

[I 2025-09-13 06:38:41,339] Trial 27 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.95367	eval-mlogloss:0.95363

[I 2025-09-13 06:38:41,355] Trial 28 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.00533	eval-mlogloss:0.99906
[1]	train-mlogloss:0.92245	eval-mlogloss:0.91236

[I 2025-09-13 06:38:41,379] Trial 29 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03564	eval-mlogloss:1.03087
[1]	train-mlogloss:0.97816	eval-mlogloss:0.97006
[2]	train-mlogloss:0.92403	eval-mlogloss:0.91384
[3]	train-mlogloss:0.87419	eval-mlogloss:0.86318

[I 2025-09-13 06:38:41,401] Trial 30 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.08299	eval-mlogloss:1.08429
[1]	train-mlogloss:1.06472	eval-mlogloss:1.06563
[2]	train-mlogloss:1.04653	eval-mlogloss:1.04641
[3]	train-mlogloss:1.02850	eval-mlogloss:1.02813
[4]	train-mlogloss:1.01116	eval-mlogloss:1.00970
[5]	train-mlogloss:0.99374	eval-mlogloss:0.99120
[6]	train-mlogloss:0.97727	eval-mlogloss:0.97529
[7]	train-mlogloss:0.96159	eval-mlogloss:0.95975
[8]	train-mlogloss:0.94588	eval-mlogloss:0.94304
[9]	train-mlogloss:0.93034	eval-mlogloss:0.92769
[10]	train-mlogloss:0.91547	eval-mlogloss:0.91330
[11]	train-mlogloss:0.90057	eval-mlogloss:0.89836
[12]	train-mlogloss:0.88918	eval-mlogloss:0.88849
[13]	train-mlogloss:0.87511	eval-mlogloss:0.87420
[14]	train-mlogloss:0.86380	eval-mlogloss:0.86369
[15]	train-mlogloss:0.85059	eval-mlogloss:0.84964
[16]	train-mlogloss:0.83780	eval-mlogloss:0.83740
[17]	train-mlogloss:0.82626	eval-mlogloss:0.82666
[18]	train-mlogloss:0.81351	eval-mlogloss:0.81363
[19]	train-mlogloss:0.80240	eval-mlogloss:0.80326
[20]	train-mlogloss:0.78979	eval-mlogloss:0.79099
[21]	train-mlogloss:0.77757	eval-mlogloss:0.77777
[22]	train-mlogloss:0.76590	eval-mlogloss:0.76640
[23]	train-mlogloss:0.75418	eval-mlogloss:0.75383
[24]	train-mlogloss:0.74292	eval-mlogloss:0.74228
[25]	train-mlogloss:0.73190	eval-mlogloss:0.73048
[26]	train-mlogloss:0.72235	eval-mlogloss:0.72221
[27]	train-mlogloss:0.71162	eval-mlogloss:0.71154
[28]	train-mlogloss:0.70193	eval-mlogloss:0.70337
[29]	train-mlogloss:0.69132	eval-mlogloss:0.69237
[30]	train-mlogloss:0.68129	eval-mlogloss:0.68212
[31]	train-mlogloss:0.67241	eval-mlogloss:0.67414
[32]	train-mlogloss:0.66265	eval-mlogloss:0.66415
[33]	train-mlogloss:0.65543	eval-mlogloss:0.65810
[34]	train-mlogloss:0.64581	eval-mlogloss:0.64807
[35]	train-mlogloss:0.63685	eval-mlogloss:0.63825
[36]	train-mlogloss:0.62875	eval-mlogloss:0.63141
[37]	train-mlogloss:0.61964	eval-mlogloss:0.62206
[38]	train-mlogloss:0.61109	eval-mlogloss:0.61447
[39]	train-mlogloss:0.60245	eval-mlogloss:0.60562
[40]	train-mlogloss:0.59529	eval-mlogloss:0.59922
[41]	train-mlogloss:0.58718	eval-mlogloss:0.59053
[42]	train-mlogloss:0.58041	eval-mlogloss:0.58401
[43]	train-mlogloss:0.57302	eval-mlogloss:0.57760
[44]	train-mlogloss:0.56510	eval-mlogloss:0.56923
[45]	train-mlogloss:0.55809	eval-mlogloss:0.56311
[46]	train-mlogloss:0.55057	eval-mlogloss:0.55528
[47]	train-mlogloss:0.54289	eval-mlogloss:0.54758
[48]	train-mlogloss:0.53538	eval-mlogloss:0.54034
[49]	train-mlogloss:0.52809	eval-mlogloss:0.53276
[50]	train-mlogloss:0.52088	eval-mlogloss:0.52536
[51]	train-mlogloss:0.51403	eval-mlogloss:0.51813
[52]	train-mlogloss:0.50732	eval-mlogloss:0.51155
[53]	train-mlogloss:0.50065	eval-mlogloss:0.50420
[54]	train-mlogloss:0.49452	eval-mlogloss:0.49841
[55]	train-mlogloss:0.48782	eval-mlogloss:0.49110
[56]	train-mlogloss:0.48163	eval-mlogloss:0.48465
[57]	train-mlogloss:0.47525	eval-mlogloss:0.47764
[58]	train-mlogloss:0.46903	eval-mlogloss:0.47081
[59]	train-mlogloss:0.46346	eval-mlogloss:0.46531
[60]	train-mlogloss:0.45749	eval-mlogloss:0.45862
[61]	train-mlogloss:0.45225	eval-mlogloss:0.45379
[62]	train-mlogloss:0.44628	eval-mlogloss:0.44825
[63]	train-mlogloss:0.44128	eval-mlogloss:0.44343
[64]	train-mlogloss:0.43636	eval-mlogloss:0.43979
[65]	train-mlogloss:0.43084	eval-mlogloss:0.43432
[66]	train-mlogloss:0.42566	eval-mlogloss:0.42870
[67]	train-mlogloss:0.42017	eval-mlogloss:0.42302
[68]	train-mlogloss:0.41567	eval-mlogloss:0.41853
[69]	train-mlogloss:0.41057	eval-mlogloss:0.41298
[70]	train-mlogloss:0.40606	eval-mlogloss:0.40897
[71]	train-mlogloss:0.40101	eval-mlogloss:0.40339
[72]	train-mlogloss:0.39582	eval-mlogloss:0.39796
[73]	train-mlogloss:0.39076	eval-mlogloss:0.39238
[74]	train-mlogloss:0.38577	eval-mlogloss:0.38770
[75]	train-mlogloss:0.38107	eval-mlogloss:0.38305
[76]	train-mlogloss:0.37631	eval-mlogloss:0.37891
[77]	train-mlogloss:0.37219	eval-mlogloss:0.37513
[78]	train-mlogloss:0.36761	eval-mlogloss:0.37012
[79]	train-mlogloss:0.36308	eval-mlogloss:0.36526
[80]	train-mlogloss:0.35867	eval-mlogloss:0.36127
[81]	train-mlogloss:0.35421	eval-mlogloss:0.35647
[82]	train-mlogloss:0.35003	eval-mlogloss:0.35185
[83]	train-mlogloss:0.34649	eval-mlogloss:0.34841
[84]	train-mlogloss:0.34226	eval-mlogloss:0.34401
[85]	train-mlogloss:0.33874	eval-mlogloss:0.34050
[86]	train-mlogloss:0.33453	eval-mlogloss:0.33610
[87]	train-mlogloss:0.33054	eval-mlogloss:0.33223
[88]	train-mlogloss:0.32665	eval-mlogloss:0.32769
[89]	train-mlogloss:0.32265	eval-mlogloss:0.32327
[90]	train-mlogloss:0.31878	eval-mlogloss:0.31890
[91]	train-mlogloss:0.31511	eval-mlogloss:0.31526
[92]	train-mlogloss:0.31124	eval-mlogloss:0.31141
[93]	train-mlogloss:0.30873	eval-mlogloss:0.30930
[94]	train-mlogloss:0.30505	eval-mlogloss:0.30521
[95]	train-mlogloss:0.30163	eval-mlogloss:0.30132
[96]	train-mlogloss:0.29820	eval-mlogloss:0.29791
[97]	train-mlogloss:0.29436	eval-mlogloss:0.29388
[98]	train-mlogloss:0.29092	eval-mlogloss:0.29024
[99]	train-mlogloss:0.28766	eval-mlogloss:0.28741
[100]	train-mlogloss:0.28429	eval-mlogloss:0.28370
[101]	train-mlogloss:0.28097	eval-mlogloss:0.28003
[102]	train-mlogloss:0.27765	eval-mlogloss:0.27641
[103]	train-mlogloss:0.27435	eval-mlogloss:0.27287
[104]	train-mlogloss:0.27120	eval-mlogloss:0.26925
[105]	train-mlogloss:0.26815	eval-mlogloss:0.26614
[106]	train-mlogloss:0.26527	eval-mlogloss:0.26329
[107]	train-mlogloss:0.26235	eval-mlogloss:0.25981
[108]	train-mlogloss:0.25991	eval-mlogloss:0.25724
[109]	train-mlogloss:0.25701	eval-mlogloss:0.25404
[110]	train-mlogloss:0.25405	eval-mlogloss:0.25057
[111]	train-mlogloss:0.25121	eval-mlogloss:0.24747
[112]	train-mlogloss:0.24841	eval-mlogloss:0.24430
[113]	train-mlogloss:0.24570	eval-mlogloss:0.24114
[114]	train-mlogloss:0.24339	eval-mlogloss:0.23909
[115]	train-mlogloss:0.24067	eval-mlogloss:0.23645
[116]	train-mlogloss:0.23794	eval-mlogloss:0.23325
[117]	train-mlogloss:0.23535	eval-mlogloss:0.23010
[118]	train-mlogloss:0.23273	eval-mlogloss:0.22812
[119]	train-mlogloss:0.23038	eval-mlogloss:0.22578
[120]	train-mlogloss:0.22783	eval-mlogloss:0.22304
[121]	train-mlogloss:0.22530	eval-mlogloss:0.22021
[122]	train-mlogloss:0.22290	eval-mlogloss:0.21744
[123]	train-mlogloss:0.22053	eval-mlogloss:0.21474
[124]	train-mlogloss:0.21817	eval-mlogloss:0.21237
[125]	train-mlogloss:0.21576	eval-mlogloss:0.20982
[126]	train-mlogloss:0.21376	eval-mlogloss:0.20793
[127]	train-mlogloss:0.21187	eval-mlogloss:0.20611
[128]	train-mlogloss:0.20950	eval-mlogloss:0.20362
[129]	train-mlogloss:0.20761	eval-mlogloss:0.20190
[130]	train-mlogloss:0.20567	eval-mlogloss:0.20015
[131]	train-mlogloss:0.20345	eval-mlogloss:0.19751
[132]	train-mlogloss:0.20129	eval-mlogloss:0.19515
[133]	train-mlogloss:0.19937	eval-mlogloss:0.19288
[134]	train-mlogloss:0.19759	eval-mlogloss:0.19089
[135]	train-mlogloss:0.19559	eval-mlogloss:0.18866
[136]	train-mlogloss:0.19345	eval-mlogloss:0.18628
[137]	train-mlogloss:0.19126	eval-mlogloss:0.18399
[138]	train-mlogloss:0.18932	eval-mlogloss:0.18184
[139]	train-mlogloss:0.18759	eval-mlogloss:0.18014
[140]	train-mlogloss:0.18572	eval-mlogloss:0.17814
[141]	train-mlogloss:0.18403	eval-mlogloss:0.17644
[142]	train-mlogloss:0.18241	eval-mlogloss:0.17492
[143]	train-mlogloss:0.18045	eval-mlogloss:0.17268
[144]	train-mlogloss:0.17845	eval-mlogloss:0.17066
[145]	train-mlogloss:0.17656	eval-mlogloss:0.16851
[146]	train-mlogloss:0.17487	eval-mlogloss:0.16655
[147]	train-mlogloss:0.17306	eval-mlogloss:0.16452
[148]	train-mlogloss:0.17139	eval-mlogloss:0.16248
[149]	train-mlogloss:0.16987	eval-mlogloss:0.16112
[150]	train-mlogloss:0.16805	eval-mlogloss:0.15950
[151]	train-mlogloss:0.16621	eval-mlogloss:0.15753
[152]	train-mlogloss:0.16459	eval-mlogloss:0.15567
[153]	train-mlogloss:0.16301	eval-mlogloss:0.15386
[154]	train-mlogloss:0.16138	eval-mlogloss:0.15204
[155]	train-mlogloss:0.15971	eval-mlogloss:0.15012
[156]	train-mlogloss:0.15819	eval-mlogloss:0.14831
[157]	train-mlogloss:0.15664	eval-mlogloss:0.14645
[158]	train-mlogloss:0.15509	eval-mlogloss:0.14456
[159]	train-mlogloss:0.15370	eval-mlogloss:0.14313
[160]	train-mlogloss:0.15221	eval-mlogloss:0.14178
[161]	train-mlogloss:0.15062	eval-mlogloss:0.14033
[162]	train-mlogloss:0.14923	eval-mlogloss:0.13912
[163]	train-mlogloss:0.14789	eval-mlogloss:0.13775
[164]	train-mlogloss:0.14681	eval-mlogloss:0.13677
[165]	train-mlogloss:0.14559	eval-mlogloss:0.13523
[166]	train-mlogloss:0.14415	eval-mlogloss:0.13357
[167]	train-mlogloss:0.14279	eval-mlogloss:0.13178
[168]	train-mlogloss:0.14165	eval-mlogloss:0.13088
[169]	train-mlogloss:0.14039	eval-mlogloss:0.12963
[170]	train-mlogloss:0.13928	eval-mlogloss:0.12843
[171]	train-mlogloss:0.13801	eval-mlogloss:0.12703
[172]	train-mlogloss:0.13692	eval-mlogloss:0.12622
[173]	train-mlogloss:0.13565	eval-mlogloss:0.12473
[174]	train-mlogloss:0.13455	eval-mlogloss:0.12364
[175]	train-mlogloss:0.13323	eval-mlogloss:0.12228
[176]	train-mlogloss:0.13203	eval-mlogloss:0.12087
[177]	train-mlogloss:0.13100	eval-mlogloss:0.12004
[178]	train-mlogloss:0.12983	eval-mlogloss:0.11894
[179]	train-mlogloss:0.12884	eval-mlogloss:0.11803
[180]	train-mlogloss:0.12770	eval-mlogloss:0.11667
[181]	train-mlogloss:0.12660	eval-mlogloss:0.11526
[182]	train-mlogloss:0.12574	eval-mlogloss:0.11427
[183]	train-mlogloss:0.12471	eval-mlogloss:0.11308
[184]	train-mlogloss:0.12354	eval-mlogloss:0.11207
[185]	train-mlogloss:0.12246	eval-mlogloss:0.11064
[186]	train-mlogloss:0.12147	eval-mlogloss:0.10996
[187]	train-mlogloss:0.12053	eval-mlogloss:0.10888
[188]	train-mlogloss:0.11953	eval-mlogloss:0.10791
[189]	train-mlogloss:0.11829	eval-mlogloss:0.10708
[190]	train-mlogloss:0.11726	eval-mlogloss:0.10590
[191]	train-mlogloss:0.11646	eval-mlogloss:0.10501
[192]	train-mlogloss:0.11533	eval-mlogloss:0.10412
[193]	train-mlogloss:0.11439	eval-mlogloss:0.10304
[194]	train-mlogloss:0.11358	eval-mlogloss:0.10232
[195]	train-mlogloss:0.11263	eval-mlogloss:0.10117
[196]	train-mlogloss:0.11178	eval-mlogloss:0.10057
[197]	train-mlogloss:0.11083	eval-mlogloss:0.09937
[198]	train-mlogloss:0.10996	eval-mlogloss:0.09820
[199]	train-mlogloss:0.10901	eval-mlogloss:0.09720
[200]	train-mlogloss:0.10794	eval-mlogloss:0.09606
[201]	train-mlogloss:0.10729	eval-mlogloss:0.09522
[202]	train-mlogloss:0.10654	eval-mlogloss:0.09486
[203]	train-mlogloss:0.10558	eval-mlogloss:0.09418
[204]	train-mlogloss:0.10484	eval-mlogloss:0.09339
[205]	train-mlogloss:0.10408	eval-mlogloss:0.09268
[206]	train-mlogloss:0.10328	eval-mlogloss:0.09177
[207]	train-mlogloss:0.10245	eval-mlogloss:0.09095
[208]	train-mlogloss:0.10159	eval-mlogloss:0.09032
[209]	train-mlogloss:0.10069	eval-mlogloss:0.08940
[210]	train-mlogloss:0.10005	eval-mlogloss:0.08876
[211]	train-mlogloss:0.09951	eval-mlogloss:0.08839
[212]	train-mlogloss:0.09868	eval-mlogloss:0.08766
[213]	train-mlogloss:0.09790	eval-mlogloss:0.08691
[214]	train-mlogloss:0.09712	eval-mlogloss:0.08618
[215]	train-mlogloss:0.09633	eval-mlogloss:0.08520
[216]	train-mlogloss:0.09551	eval-mlogloss:0.08425
[217]	train-mlogloss:0.09472	eval-mlogloss:0.08322
[218]	train-mlogloss:0.09421	eval-mlogloss:0.08274
[219]	train-mlogloss:0.09336	eval-mlogloss:0.08204
[220]	train-mlogloss:0.09283	eval-mlogloss:0.08157
[221]	train-mlogloss:0.09224	eval-mlogloss:0.08101
[222]	train-mlogloss:0.09149	eval-mlogloss:0.08040
[223]	train-mlogloss:0.09095	eval-mlogloss:0.07986
[224]	train-mlogloss:0.09028	eval-mlogloss:0.07939
[225]	train-mlogloss:0.08972	eval-mlogloss:0.07877
[226]	train-mlogloss:0.08906	eval-mlogloss:0.07818
[227]	train-mlogloss:0.08830	eval-mlogloss:0.07759
[228]	train-mlogloss:0.08759	eval-mlogloss:0.07692
[229]	train-mlogloss:0.08694	eval-mlogloss:0.07620
[230]	train-mlogloss:0.08636	eval-mlogloss:0.07536
[231]	train-mlogloss:0.08583	eval-mlogloss:0.07469
[232]	train-mlogloss:0.08531	eval-mlogloss:0.07414
[233]	train-mlogloss:0.08481	eval-mlogloss:0.07386
[234]	train-mlogloss:0.08430	eval-mlogloss:0.07325
[235]	train-mlogloss:0.08382	eval-mlogloss:0.07261
[236]	train-mlogloss:0.08319	eval-mlogloss:0.07202
[237]	train-mlogloss:0.08258	eval-mlogloss:0.07141
[238]	train-mlogloss:0.08208	eval-mlogloss:0.07080
[239]	train-mlogloss:0.08164	eval-mlogloss:0.07026
[240]	train-mlogloss:0.08108	eval-mlogloss:0.06958
[241]	train-mlogloss:0.08068	eval-mlogloss:0.06944
[242]	train-mlogloss:0.08021	eval-mlogloss:0.06901
[243]	train-mlogloss:0.07979	eval-mlogloss:0.06866
[244]	train-mlogloss:0.07918	eval-mlogloss:0.06810
[245]	train-mlogloss:0.07862	eval-mlogloss:0.06742
[246]	train-mlogloss:0.07829	eval-mlogloss:0.06709
[247]	train-mlogloss:0.07788	eval-mlogloss:0.06667
[248]	train-mlogloss:0.07745	eval-mlogloss:0.06611
[249]	train-mlogloss:0.07697	eval-mlogloss:0.06545
[250]	train-mlogloss:0.07641	eval-mlogloss:0.06467
[251]	train-mlogloss:0.07608	eval-mlogloss:0.06425
[252]	train-mlogloss:0.07560	eval-mlogloss:0.06368
[253]	train-mlogloss:0.07520	eval-mlogloss:0.06318
[254]	train-mlogloss:0.07485	eval-mlogloss:0.06275
[255]	train-mlogloss:0.07453	eval-mlogloss:0.06244
[256]	train-mlogloss:0.07420	eval-mlogloss:0.06199
[257]	train-mlogloss:0.07372	eval-mlogloss:0.06165
[258]	train-mlogloss:0.07338	eval-mlogloss:0.06125
[259]	train-mlogloss:0.07305	eval-mlogloss:0.06100
[260]	train-mlogloss:0.07247	eval-mlogloss:0.06073
[261]	train-mlogloss:0.07213	eval-mlogloss:0.06044
[262]	train-mlogloss:0.07172	eval-mlogloss:0.05995
[263]	train-mlogloss:0.07139	eval-mlogloss:0.05969
[264]	train-mlogloss:0.07109	eval-mlogloss:0.05926
[265]	train-mlogloss:0.07078	eval-mlogloss:0.05901
[266]	train-mlogloss:0.07042	eval-mlogloss:0.05869
[267]	train-mlogloss:0.07004	eval-mlogloss:0.05853
[268]	train-mlogloss:0.06971	eval-mlogloss:0.05799
[269]	train-mlogloss:0.06920	eval-mlogloss:0.05752
[270]	train-mlogloss:0.06886	eval-mlogloss:0.05738
[271]	train-mlogloss:0.06847	eval-mlogloss:0.05704
[272]	train-mlogloss:0.06808	eval-mlogloss:0.05653
[273]	train-mlogloss:0.06776	eval-mlogloss:0.05624
[274]	train-mlogloss:0.06747	eval-mlogloss:0.05583
[275]	train-mlogloss:0.06707	eval-mlogloss:0.05541
[276]	train-mlogloss:0.06672	eval-mlogloss:0.05499
[277]	train-mlogloss:0.06639	eval-mlogloss:0.05477
[278]	train-mlogloss:0.06611	eval-mlogloss:0.05451
[279]	train-mlogloss:0.06573	eval-mlogloss:0.05386
[280]	train-mlogloss:0.06540	eval-mlogloss:0.05335
[281]	train-mlogloss:0.06502	eval-mlogloss:0.05308
[282]	train-mlogloss:0.06468	eval-mlogloss:0.05278
[283]	train-mlogloss:0.06450	eval-mlogloss:0.05277
[284]	train-mlogloss:0.06419	eval-mlogloss:0.05253
[285]	train-mlogloss:0.06392	eval-mlogloss:0.05237
[286]	train-mlogloss:0.06359	eval-mlogloss:0.05187
[287]	train-mlogloss:0.06327	eval-mlogloss:0.05145
[288]	train-mlogloss:0.06289	eval-mlogloss:0.05090
[289]	train-mlogloss:0.06265	eval-mlogloss:0.05086
[290]	train-mlogloss:0.06234	eval-mlogloss:0.05057
[291]	train-mlogloss:0.06207	eval-mlogloss:0.05038
[292]	train-mlogloss:0.06182	eval-mlogloss:0.05015
[293]	train-mlogloss:0.06153	eval-mlogloss:0.04986
[294]	train-mlogloss:0.06123	eval-mlogloss:0.04954
[295]	train-mlogloss:0.06094	eval-mlogloss:0.04929
[296]	train-mlogloss:0.06069	eval-mlogloss:0.04899
[297]	train-mlogloss:0.06042	eval-mlogloss:0.04865
[298]	train-mlogloss:0.06016	eval-mlogloss:0.04816
[299]	train-mlogloss:0.05985	eval-mlogloss:0.04760

[I 2025-09-13 06:38:42,278] Trial 31 finished with value: 1.0 and parameters: {'lambda': 0.009238848376451921, 'alpha': 0.022040464647133266, 'eta': 0.01405615945337832, 'gamma': 0.0010239779725597004, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.7496864116787847, 'colsample_bytree': 0.5122069816595376}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.08228	eval-mlogloss:1.08479
[1]	train-mlogloss:1.04590	eval-mlogloss:1.04677
[2]	train-mlogloss:1.01054	eval-mlogloss:1.00975
[3]	train-mlogloss:0.98431	eval-mlogloss:0.98200
[4]	train-mlogloss:0.95718	eval-mlogloss:0.95538

[I 2025-09-13 06:38:42,327] Trial 32 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.08870	eval-mlogloss:1.08818
[1]	train-mlogloss:1.07605	eval-mlogloss:1.07509
[2]	train-mlogloss:1.06330	eval-mlogloss:1.06162
[3]	train-mlogloss:1.05034	eval-mlogloss:1.04853
[4]	train-mlogloss:1.03808	eval-mlogloss:1.03611
[5]	train-mlogloss:1.02537	eval-mlogloss:1.02277
[6]	train-mlogloss:1.01342	eval-mlogloss:1.01052
[7]	train-mlogloss:1.00201	eval-mlogloss:0.99890
[8]	train-mlogloss:0.99053	eval-mlogloss:0.98679
[9]	train-mlogloss:0.97917	eval-mlogloss:0.97527
[10]	train-mlogloss:0.96797	eval-mlogloss:0.96433
[11]	train-mlogloss:0.95716	eval-mlogloss:0.95292
[12]	train-mlogloss:0.94945	eval-mlogloss:0.94653
[13]	train-mlogloss:0.93896	eval-mlogloss:0.93560
[14]	train-mlogloss:0.93075	eval-mlogloss:0.92784
[15]	train-mlogloss:0.92108	eval-mlogloss:0.91771
[16]	train-mlogloss:0.91181	eval-mlogloss:0.90801
[17]	train-mlogloss:0.90354	eval-mlogloss:0.89979
[18]	train-mlogloss:0.89416	eval-mlogloss:0.89007
[19]	train-mlogloss:0.88573	eval-mlogloss:0.88205
[20]	train-mlogloss:0.87595	eval-mlogloss:0.87180
[21]	train-mlogloss:0.86627	eval-mlogloss:0.86139
[22]	train-mlogloss:0.85728	eval-mlogloss:0.85223
[23]	train-mlogloss:0.84799	eval-mlogloss:0.84236
[24]	train-mlogloss:0.83894	eval-mlogloss:0.83278
[25]	train-mlogloss:0.83003	eval-mlogloss:0.82300
[26]	train-mlogloss:0.82244	eval-mlogloss:0.81582
[27]	train-mlogloss:0.81377	eval-mlogloss:0.80691
[28]	train-mlogloss:0.80631	eval-mlogloss:0.79944
[29]	train-mlogloss:0.79761	eval-mlogloss:0.79026
[30]	train-mlogloss:0.78942	eval-mlogloss:0.78159
[31]	train-mlogloss:0.78217	eval-mlogloss:0.77444
[32]	train-mlogloss:0.77414	eval-mlogloss:0.76572
[33]	train-mlogloss:0.76871	eval-mlogloss:0.76028
[34]	train-mlogloss:0.76073	eval-mlogloss:0.75199
[35]	train-mlogloss:0.75323	eval-mlogloss:0.74364
[36]	train-mlogloss:0.74651	eval-mlogloss:0.73732
[37]	train-mlogloss:0.73907	eval-mlogloss:0.72975
[38]	train-mlogloss:0.73227	eval-mlogloss:0.72307
[39]	train-mlogloss:0.72520	eval-mlogloss:0.71569
[40]	train-mlogloss:0.71909	eval-mlogloss:0.71000
[41]	train-mlogloss:0.71191	eval-mlogloss:0.70233
[42]	train-mlogloss:0.70662	eval-mlogloss:0.69677
[43]	train-mlogloss:0.70044	eval-mlogloss:0.69121
[44]	train-mlogloss:0.69343	eval-mlogloss:0.68376
[45]	train-mlogloss:0.68750	eval-mlogloss:0.67813
[46]	train-mlogloss:0.68072	eval-mlogloss:0.67087
[47]	train-mlogloss:0.67403	eval-mlogloss:0.66404
[48]	train-mlogloss:0.66732	eval-mlogloss:0.65718
[49]	train-mlogloss:0.66070	eval-mlogloss:0.65029
[50]	train-mlogloss:0.65421	eval-mlogloss:0.64335
[51]	train-mlogloss:0.64796	eval-mlogloss:0.63649
[52]	train-mlogloss:0.64214	eval-mlogloss:0.63039
[53]	train-mlogloss:0.63606	eval-mlogloss:0.62374
[54]	train-mlogloss:0.63065	eval-mlogloss:0.61832
[55]	train-mlogloss:0.62451	eval-mlogloss:0.61166
[56]	train-mlogloss:0.61887	eval-mlogloss:0.60562
[57]	train-mlogloss:0.61300	eval-mlogloss:0.59939
[58]	train-mlogloss:0.60734	eval-mlogloss:0.59327
[59]	train-mlogloss:0.60225	eval-mlogloss:0.58822
[60]	train-mlogloss:0.59669	eval-mlogloss:0.58211
[61]	train-mlogloss:0.59214	eval-mlogloss:0.57778
[62]	train-mlogloss:0.58654	eval-mlogloss:0.57202
[63]	train-mlogloss:0.58189	eval-mlogloss:0.56735
[64]	train-mlogloss:0.57775	eval-mlogloss:0.56285
[65]	train-mlogloss:0.57228	eval-mlogloss:0.55709
[66]	train-mlogloss:0.56730	eval-mlogloss:0.55182
[67]	train-mlogloss:0.56195	eval-mlogloss:0.54680
[68]	train-mlogloss:0.55785	eval-mlogloss:0.54267
[69]	train-mlogloss:0.55295	eval-mlogloss:0.53721
[70]	train-mlogloss:0.54887	eval-mlogloss:0.53346
[71]	train-mlogloss:0.54385	eval-mlogloss:0.52807
[72]	train-mlogloss:0.53898	eval-mlogloss:0.52311
[73]	train-mlogloss:0.53400	eval-mlogloss:0.51779
[74]	train-mlogloss:0.52922	eval-mlogloss:0.51269
[75]	train-mlogloss:0.52479	eval-mlogloss:0.50802
[76]	train-mlogloss:0.52016	eval-mlogloss:0.50308
[77]	train-mlogloss:0.51617	eval-mlogloss:0.49914
[78]	train-mlogloss:0.51170	eval-mlogloss:0.49411
[79]	train-mlogloss:0.50705	eval-mlogloss:0.48917
[80]	train-mlogloss:0.50256	eval-mlogloss:0.48484
[81]	train-mlogloss:0.49786	eval-mlogloss:0.47989
[82]	train-mlogloss:0.49371	eval-mlogloss:0.47521
[83]	train-mlogloss:0.49022	eval-mlogloss:0.47171
[84]	train-mlogloss:0.48584	eval-mlogloss:0.46701
[85]	train-mlogloss:0.48215	eval-mlogloss:0.46343
[86]	train-mlogloss:0.47781	eval-mlogloss:0.45869
[87]	train-mlogloss:0.47387	eval-mlogloss:0.45454
[88]	train-mlogloss:0.46966	eval-mlogloss:0.44997
[89]	train-mlogloss:0.46550	eval-mlogloss:0.44582
[90]	train-mlogloss:0.46146	eval-mlogloss:0.44142
[91]	train-mlogloss:0.45757	eval-mlogloss:0.43744
[92]	train-mlogloss:0.45356	eval-mlogloss:0.43321
[93]	train-mlogloss:0.45094	eval-mlogloss:0.43091
[94]	train-mlogloss:0.44705	eval-mlogloss:0.42686
[95]	train-mlogloss:0.44329	eval-mlogloss:0.42263
[96]	train-mlogloss:0.43958	eval-mlogloss:0.41900
[97]	train-mlogloss:0.43561	eval-mlogloss:0.41480
[98]	train-mlogloss:0.43199	eval-mlogloss:0.41071
[99]	train-mlogloss:0.42875	eval-mlogloss:0.40744
[100]	train-mlogloss:0.42508	eval-mlogloss:0.40345
[101]	train-mlogloss:0.42146	eval-mlogloss:0.39954
[102]	train-mlogloss:0.41785	eval-mlogloss:0.39565
[103]	train-mlogloss:0.41428	eval-mlogloss:0.39214
[104]	train-mlogloss:0.41079	eval-mlogloss:0.38837
[105]	train-mlogloss:0.40744	eval-mlogloss:0.38492
[106]	train-mlogloss:0.40437	eval-mlogloss:0.38168
[107]	train-mlogloss:0.40095	eval-mlogloss:0.37786
[108]	train-mlogloss:0.39832	eval-mlogloss:0.37537
[109]	train-mlogloss:0.39511	eval-mlogloss:0.37195
[110]	train-mlogloss:0.39185	eval-mlogloss:0.36846
[111]	train-mlogloss:0.38866	eval-mlogloss:0.36508
[112]	train-mlogloss:0.38537	eval-mlogloss:0.36150
[113]	train-mlogloss:0.38227	eval-mlogloss:0.35798
[114]	train-mlogloss:0.37997	eval-mlogloss:0.35543
[115]	train-mlogloss:0.37681	eval-mlogloss:0.35235
[116]	train-mlogloss:0.37383	eval-mlogloss:0.34908
[117]	train-mlogloss:0.37067	eval-mlogloss:0.34550
[118]	train-mlogloss:0.36758	eval-mlogloss:0.34264
[119]	train-mlogloss:0.36491	eval-mlogloss:0.34011
[120]	train-mlogloss:0.36187	eval-mlogloss:0.33717
[121]	train-mlogloss:0.35886	eval-mlogloss:0.33392
[122]	train-mlogloss:0.35598	eval-mlogloss:0.33087
[123]	train-mlogloss:0.35326	eval-mlogloss:0.32786
[124]	train-mlogloss:0.35044	eval-mlogloss:0.32482
[125]	train-mlogloss:0.34761	eval-mlogloss:0.32169
[126]	train-mlogloss:0.34551	eval-mlogloss:0.31957
[127]	train-mlogloss:0.34330	eval-mlogloss:0.31738
[128]	train-mlogloss:0.34046	eval-mlogloss:0.31442
[129]	train-mlogloss:0.33835	eval-mlogloss:0.31229
[130]	train-mlogloss:0.33602	eval-mlogloss:0.31012
[131]	train-mlogloss:0.33328	eval-mlogloss:0.30709
[132]	train-mlogloss:0.33064	eval-mlogloss:0.30434
[133]	train-mlogloss:0.32831	eval-mlogloss:0.30185
[134]	train-mlogloss:0.32611	eval-mlogloss:0.29945
[135]	train-mlogloss:0.32376	eval-mlogloss:0.29669
[136]	train-mlogloss:0.32119	eval-mlogloss:0.29398
[137]	train-mlogloss:0.31870	eval-mlogloss:0.29139
[138]	train-mlogloss:0.31622	eval-mlogloss:0.28877
[139]	train-mlogloss:0.31420	eval-mlogloss:0.28679
[140]	train-mlogloss:0.31188	eval-mlogloss:0.28439
[141]	train-mlogloss:0.31007	eval-mlogloss:0.28242
[142]	train-mlogloss:0.30807	eval-mlogloss:0.28030
[143]	train-mlogloss:0.30572	eval-mlogloss:0.27779
[144]	train-mlogloss:0.30336	eval-mlogloss:0.27522
[145]	train-mlogloss:0.30102	eval-mlogloss:0.27273
[146]	train-mlogloss:0.29872	eval-mlogloss:0.27022
[147]	train-mlogloss:0.29643	eval-mlogloss:0.26781
[148]	train-mlogloss:0.29422	eval-mlogloss:0.26536
[149]	train-mlogloss:0.29227	eval-mlogloss:0.26365
[150]	train-mlogloss:0.29009	eval-mlogloss:0.26132
[151]	train-mlogloss:0.28790	eval-mlogloss:0.25904
[152]	train-mlogloss:0.28582	eval-mlogloss:0.25662
[153]	train-mlogloss:0.28378	eval-mlogloss:0.25439
[154]	train-mlogloss:0.28171	eval-mlogloss:0.25211
[155]	train-mlogloss:0.27952	eval-mlogloss:0.24973
[156]	train-mlogloss:0.27745	eval-mlogloss:0.24728
[157]	train-mlogloss:0.27538	eval-mlogloss:0.24500
[158]	train-mlogloss:0.27338	eval-mlogloss:0.24274
[159]	train-mlogloss:0.27162	eval-mlogloss:0.24071
[160]	train-mlogloss:0.26982	eval-mlogloss:0.23861
[161]	train-mlogloss:0.26782	eval-mlogloss:0.23659
[162]	train-mlogloss:0.26604	eval-mlogloss:0.23473
[163]	train-mlogloss:0.26427	eval-mlogloss:0.23289
[164]	train-mlogloss:0.26289	eval-mlogloss:0.23142
[165]	train-mlogloss:0.26116	eval-mlogloss:0.22960
[166]	train-mlogloss:0.25925	eval-mlogloss:0.22753
[167]	train-mlogloss:0.25740	eval-mlogloss:0.22545
[168]	train-mlogloss:0.25602	eval-mlogloss:0.22422
[169]	train-mlogloss:0.25430	eval-mlogloss:0.22233
[170]	train-mlogloss:0.25278	eval-mlogloss:0.22077
[171]	train-mlogloss:0.25100	eval-mlogloss:0.21877
[172]	train-mlogloss:0.24948	eval-mlogloss:0.21781
[173]	train-mlogloss:0.24778	eval-mlogloss:0.21580
[174]	train-mlogloss:0.24628	eval-mlogloss:0.21409
[175]	train-mlogloss:0.24452	eval-mlogloss:0.21251
[176]	train-mlogloss:0.24291	eval-mlogloss:0.21071
[177]	train-mlogloss:0.24165	eval-mlogloss:0.20948
[178]	train-mlogloss:0.23997	eval-mlogloss:0.20785
[179]	train-mlogloss:0.23864	eval-mlogloss:0.20656
[180]	train-mlogloss:0.23702	eval-mlogloss:0.20474
[181]	train-mlogloss:0.23537	eval-mlogloss:0.20290
[182]	train-mlogloss:0.23415	eval-mlogloss:0.20152
[183]	train-mlogloss:0.23270	eval-mlogloss:0.19991
[184]	train-mlogloss:0.23111	eval-mlogloss:0.19830
[185]	train-mlogloss:0.22954	eval-mlogloss:0.19657
[186]	train-mlogloss:0.22827	eval-mlogloss:0.19559
[187]	train-mlogloss:0.22691	eval-mlogloss:0.19420
[188]	train-mlogloss:0.22553	eval-mlogloss:0.19284
[189]	train-mlogloss:0.22400	eval-mlogloss:0.19113
[190]	train-mlogloss:0.22249	eval-mlogloss:0.18945
[191]	train-mlogloss:0.22136	eval-mlogloss:0.18833
[192]	train-mlogloss:0.21983	eval-mlogloss:0.18670
[193]	train-mlogloss:0.21846	eval-mlogloss:0.18527
[194]	train-mlogloss:0.21740	eval-mlogloss:0.18411
[195]	train-mlogloss:0.21600	eval-mlogloss:0.18264
[196]	train-mlogloss:0.21482	eval-mlogloss:0.18182
[197]	train-mlogloss:0.21344	eval-mlogloss:0.18014
[198]	train-mlogloss:0.21212	eval-mlogloss:0.17863
[199]	train-mlogloss:0.21075	eval-mlogloss:0.17728
[200]	train-mlogloss:0.20939	eval-mlogloss:0.17573
[201]	train-mlogloss:0.20834	eval-mlogloss:0.17455
[202]	train-mlogloss:0.20733	eval-mlogloss:0.17378
[203]	train-mlogloss:0.20603	eval-mlogloss:0.17236
[204]	train-mlogloss:0.20499	eval-mlogloss:0.17133
[205]	train-mlogloss:0.20392	eval-mlogloss:0.17030
[206]	train-mlogloss:0.20273	eval-mlogloss:0.16910
[207]	train-mlogloss:0.20156	eval-mlogloss:0.16783
[208]	train-mlogloss:0.20024	eval-mlogloss:0.16685
[209]	train-mlogloss:0.19899	eval-mlogloss:0.16554
[210]	train-mlogloss:0.19790	eval-mlogloss:0.16472
[211]	train-mlogloss:0.19714	eval-mlogloss:0.16405
[212]	train-mlogloss:0.19586	eval-mlogloss:0.16299
[213]	train-mlogloss:0.19461	eval-mlogloss:0.16188
[214]	train-mlogloss:0.19355	eval-mlogloss:0.16062
[215]	train-mlogloss:0.19235	eval-mlogloss:0.15923
[216]	train-mlogloss:0.19112	eval-mlogloss:0.15798
[217]	train-mlogloss:0.18989	eval-mlogloss:0.15662
[218]	train-mlogloss:0.18914	eval-mlogloss:0.15591
[219]	train-mlogloss:0.18793	eval-mlogloss:0.15476
[220]	train-mlogloss:0.18709	eval-mlogloss:0.15397
[221]	train-mlogloss:0.18620	eval-mlogloss:0.15312
[222]	train-mlogloss:0.18497	eval-mlogloss:0.15209
[223]	train-mlogloss:0.18415	eval-mlogloss:0.15126
[224]	train-mlogloss:0.18321	eval-mlogloss:0.15034
[225]	train-mlogloss:0.18226	eval-mlogloss:0.14925
[226]	train-mlogloss:0.18124	eval-mlogloss:0.14820
[227]	train-mlogloss:0.18021	eval-mlogloss:0.14720
[228]	train-mlogloss:0.17904	eval-mlogloss:0.14602
[229]	train-mlogloss:0.17807	eval-mlogloss:0.14503
[230]	train-mlogloss:0.17707	eval-mlogloss:0.14398
[231]	train-mlogloss:0.17615	eval-mlogloss:0.14292
[232]	train-mlogloss:0.17536	eval-mlogloss:0.14209
[233]	train-mlogloss:0.17457	eval-mlogloss:0.14143
[234]	train-mlogloss:0.17354	eval-mlogloss:0.14023
[235]	train-mlogloss:0.17265	eval-mlogloss:0.13919
[236]	train-mlogloss:0.17165	eval-mlogloss:0.13806
[237]	train-mlogloss:0.17063	eval-mlogloss:0.13708
[238]	train-mlogloss:0.16971	eval-mlogloss:0.13605
[239]	train-mlogloss:0.16889	eval-mlogloss:0.13517
[240]	train-mlogloss:0.16788	eval-mlogloss:0.13403
[241]	train-mlogloss:0.16726	eval-mlogloss:0.13369
[242]	train-mlogloss:0.16640	eval-mlogloss:0.13287
[243]	train-mlogloss:0.16570	eval-mlogloss:0.13218
[244]	train-mlogloss:0.16486	eval-mlogloss:0.13144
[245]	train-mlogloss:0.16392	eval-mlogloss:0.13035
[246]	train-mlogloss:0.16325	eval-mlogloss:0.12978
[247]	train-mlogloss:0.16245	eval-mlogloss:0.12903
[248]	train-mlogloss:0.16161	eval-mlogloss:0.12812
[249]	train-mlogloss:0.16079	eval-mlogloss:0.12711
[250]	train-mlogloss:0.15992	eval-mlogloss:0.12612
[251]	train-mlogloss:0.15930	eval-mlogloss:0.12546
[252]	train-mlogloss:0.15840	eval-mlogloss:0.12446
[253]	train-mlogloss:0.15772	eval-mlogloss:0.12380
[254]	train-mlogloss:0.15696	eval-mlogloss:0.12302
[255]	train-mlogloss:0.15636	eval-mlogloss:0.12254
[256]	train-mlogloss:0.15588	eval-mlogloss:0.12200
[257]	train-mlogloss:0.15513	eval-mlogloss:0.12111
[258]	train-mlogloss:0.15459	eval-mlogloss:0.12058
[259]	train-mlogloss:0.15405	eval-mlogloss:0.12013
[260]	train-mlogloss:0.15299	eval-mlogloss:0.11952
[261]	train-mlogloss:0.15233	eval-mlogloss:0.11879
[262]	train-mlogloss:0.15167	eval-mlogloss:0.11812
[263]	train-mlogloss:0.15104	eval-mlogloss:0.11753
[264]	train-mlogloss:0.15043	eval-mlogloss:0.11690
[265]	train-mlogloss:0.14983	eval-mlogloss:0.11634
[266]	train-mlogloss:0.14925	eval-mlogloss:0.11573
[267]	train-mlogloss:0.14874	eval-mlogloss:0.11540
[268]	train-mlogloss:0.14806	eval-mlogloss:0.11458
[269]	train-mlogloss:0.14732	eval-mlogloss:0.11375
[270]	train-mlogloss:0.14675	eval-mlogloss:0.11325
[271]	train-mlogloss:0.14609	eval-mlogloss:0.11275
[272]	train-mlogloss:0.14537	eval-mlogloss:0.11186
[273]	train-mlogloss:0.14484	eval-mlogloss:0.11136
[274]	train-mlogloss:0.14432	eval-mlogloss:0.11071
[275]	train-mlogloss:0.14366	eval-mlogloss:0.11001
[276]	train-mlogloss:0.14304	eval-mlogloss:0.10928
[277]	train-mlogloss:0.14236	eval-mlogloss:0.10866
[278]	train-mlogloss:0.14187	eval-mlogloss:0.10815
[279]	train-mlogloss:0.14112	eval-mlogloss:0.10722
[280]	train-mlogloss:0.14053	eval-mlogloss:0.10657
[281]	train-mlogloss:0.13984	eval-mlogloss:0.10604
[282]	train-mlogloss:0.13920	eval-mlogloss:0.10536
[283]	train-mlogloss:0.13887	eval-mlogloss:0.10514
[284]	train-mlogloss:0.13822	eval-mlogloss:0.10457
[285]	train-mlogloss:0.13763	eval-mlogloss:0.10423
[286]	train-mlogloss:0.13705	eval-mlogloss:0.10350
[287]	train-mlogloss:0.13647	eval-mlogloss:0.10291
[288]	train-mlogloss:0.13584	eval-mlogloss:0.10211
[289]	train-mlogloss:0.13539	eval-mlogloss:0.10190
[290]	train-mlogloss:0.13488	eval-mlogloss:0.10147
[291]	train-mlogloss:0.13435	eval-mlogloss:0.10113
[292]	train-mlogloss:0.13392	eval-mlogloss:0.10085
[293]	train-mlogloss:0.13335	eval-mlogloss:0.10032
[294]	train-mlogloss:0.13276	eval-mlogloss:0.09972
[295]	train-mlogloss:0.13226	eval-mlogloss:0.09928
[296]	train-mlogloss:0.13179	eval-mlogloss:0.09878
[297]	train-mlogloss:0.13118	eval-mlogloss:0.09811
[298]	train-mlogloss:0.13068	eval-mlogloss:0.09740
[299]	train-mlogloss:0.13009	eval-mlogloss:0.09664

[I 2025-09-13 06:38:43,257] Trial 33 finished with value: 1.0 and parameters: {'lambda': 0.2203584556811385, 'alpha': 0.02116456193157349, 'eta': 0.01007099792374649, 'gamma': 5.3254188586851e-05, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6838902546595729, 'colsample_bytree': 0.5374701257402317}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.03374	eval-mlogloss:1.03890
[1]	train-mlogloss:0.96199	eval-mlogloss:0.96531

[I 2025-09-13 06:38:43,279] Trial 34 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.04394	eval-mlogloss:1.05053
[1]	train-mlogloss:0.93495	eval-mlogloss:0.93530

[I 2025-09-13 06:38:43,299] Trial 35 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06571	eval-mlogloss:1.06678
[1]	train-mlogloss:1.01967	eval-mlogloss:1.01874
[2]	train-mlogloss:0.97606	eval-mlogloss:0.97316
[3]	train-mlogloss:0.93431	eval-mlogloss:0.93043
[4]	train-mlogloss:0.89554	eval-mlogloss:0.89074

[I 2025-09-13 06:38:43,326] Trial 36 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.03603	eval-mlogloss:1.02620
[1]	train-mlogloss:0.94323	eval-mlogloss:0.92935

[I 2025-09-13 06:38:43,349] Trial 37 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03620	eval-mlogloss:1.04139
[1]	train-mlogloss:0.90695	eval-mlogloss:0.90030

[I 2025-09-13 06:38:43,375] Trial 38 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.00802	eval-mlogloss:1.02021

[I 2025-09-13 06:38:43,400] Trial 39 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.00261	eval-mlogloss:0.99853

[I 2025-09-13 06:38:43,421] Trial 40 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07849	eval-mlogloss:1.08012
[1]	train-mlogloss:1.05515	eval-mlogloss:1.05626
[2]	train-mlogloss:1.03208	eval-mlogloss:1.03187
[3]	train-mlogloss:1.00937	eval-mlogloss:1.00887

[I 2025-09-13 06:38:43,453] Trial 41 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.09256	eval-mlogloss:1.09340
[1]	train-mlogloss:1.07873	eval-mlogloss:1.07908
[2]	train-mlogloss:1.06478	eval-mlogloss:1.06450
[3]	train-mlogloss:1.05407	eval-mlogloss:1.05324
[4]	train-mlogloss:1.04270	eval-mlogloss:1.04209
[5]	train-mlogloss:1.02950	eval-mlogloss:1.02831
[6]	train-mlogloss:1.01933	eval-mlogloss:1.01820
[7]	train-mlogloss:1.01135	eval-mlogloss:1.01079
[8]	train-mlogloss:0.99883	eval-mlogloss:0.99775
[9]	train-mlogloss:0.98920	eval-mlogloss:0.98786
[10]	train-mlogloss:0.97697	eval-mlogloss:0.97525
[11]	train-mlogloss:0.96624	eval-mlogloss:0.96436
[12]	train-mlogloss:0.96109	eval-mlogloss:0.95952
[13]	train-mlogloss:0.94966	eval-mlogloss:0.94717
[14]	train-mlogloss:0.94520	eval-mlogloss:0.94360
[15]	train-mlogloss:0.93810	eval-mlogloss:0.93700
[16]	train-mlogloss:0.93080	eval-mlogloss:0.92960
[17]	train-mlogloss:0.92219	eval-mlogloss:0.92107
[18]	train-mlogloss:0.91539	eval-mlogloss:0.91475
[19]	train-mlogloss:0.90861	eval-mlogloss:0.90834
[20]	train-mlogloss:0.89790	eval-mlogloss:0.89704
[21]	train-mlogloss:0.89010	eval-mlogloss:0.88932
[22]	train-mlogloss:0.88331	eval-mlogloss:0.88235
[23]	train-mlogloss:0.87287	eval-mlogloss:0.87122
[24]	train-mlogloss:0.86627	eval-mlogloss:0.86489
[25]	train-mlogloss:0.85837	eval-mlogloss:0.85657
[26]	train-mlogloss:0.84996	eval-mlogloss:0.84847
[27]	train-mlogloss:0.84692	eval-mlogloss:0.84621
[28]	train-mlogloss:0.84323	eval-mlogloss:0.84317
[29]	train-mlogloss:0.83556	eval-mlogloss:0.83486
[30]	train-mlogloss:0.82831	eval-mlogloss:0.82741
[31]	train-mlogloss:0.82553	eval-mlogloss:0.82563
[32]	train-mlogloss:0.82039	eval-mlogloss:0.82124
[33]	train-mlogloss:0.81567	eval-mlogloss:0.81703
[34]	train-mlogloss:0.80753	eval-mlogloss:0.80842
[35]	train-mlogloss:0.80248	eval-mlogloss:0.80316
[36]	train-mlogloss:0.79780	eval-mlogloss:0.79930
[37]	train-mlogloss:0.79128	eval-mlogloss:0.79306
[38]	train-mlogloss:0.78435	eval-mlogloss:0.78587
[39]	train-mlogloss:0.77868	eval-mlogloss:0.78083
[40]	train-mlogloss:0.77546	eval-mlogloss:0.77794
[41]	train-mlogloss:0.76894	eval-mlogloss:0.77095
[42]	train-mlogloss:0.76650	eval-mlogloss:0.76934
[43]	train-mlogloss:0.76023	eval-mlogloss:0.76314
[44]	train-mlogloss:0.75384	eval-mlogloss:0.75648
[45]	train-mlogloss:0.74967	eval-mlogloss:0.75239
[46]	train-mlogloss:0.74339	eval-mlogloss:0.74581
[47]	train-mlogloss:0.73858	eval-mlogloss:0.74132
[48]	train-mlogloss:0.73181	eval-mlogloss:0.73462
[49]	train-mlogloss:0.72512	eval-mlogloss:0.72802
[50]	train-mlogloss:0.71884	eval-mlogloss:0.72117
[51]	train-mlogloss:0.71496	eval-mlogloss:0.71756
[52]	train-mlogloss:0.71096	eval-mlogloss:0.71399
[53]	train-mlogloss:0.70345	eval-mlogloss:0.70572
[54]	train-mlogloss:0.69960	eval-mlogloss:0.70213
[55]	train-mlogloss:0.69206	eval-mlogloss:0.69420
[56]	train-mlogloss:0.68621	eval-mlogloss:0.68808
[57]	train-mlogloss:0.67898	eval-mlogloss:0.68018
[58]	train-mlogloss:0.67500	eval-mlogloss:0.67618
[59]	train-mlogloss:0.67216	eval-mlogloss:0.67370
[60]	train-mlogloss:0.66681	eval-mlogloss:0.66787
[61]	train-mlogloss:0.66237	eval-mlogloss:0.66313
[62]	train-mlogloss:0.65537	eval-mlogloss:0.65584
[63]	train-mlogloss:0.65153	eval-mlogloss:0.65189
[64]	train-mlogloss:0.64907	eval-mlogloss:0.64972
[65]	train-mlogloss:0.64509	eval-mlogloss:0.64600
[66]	train-mlogloss:0.63973	eval-mlogloss:0.64042
[67]	train-mlogloss:0.63553	eval-mlogloss:0.63614
[68]	train-mlogloss:0.63305	eval-mlogloss:0.63427
[69]	train-mlogloss:0.62661	eval-mlogloss:0.62731
[70]	train-mlogloss:0.62258	eval-mlogloss:0.62312
[71]	train-mlogloss:0.61619	eval-mlogloss:0.61615
[72]	train-mlogloss:0.61124	eval-mlogloss:0.61094
[73]	train-mlogloss:0.60733	eval-mlogloss:0.60696
[74]	train-mlogloss:0.60287	eval-mlogloss:0.60249
[75]	train-mlogloss:0.59767	eval-mlogloss:0.59664
[76]	train-mlogloss:0.59451	eval-mlogloss:0.59352
[77]	train-mlogloss:0.59169	eval-mlogloss:0.59108
[78]	train-mlogloss:0.58860	eval-mlogloss:0.58833
[79]	train-mlogloss:0.58583	eval-mlogloss:0.58602
[80]	train-mlogloss:0.58261	eval-mlogloss:0.58299
[81]	train-mlogloss:0.57800	eval-mlogloss:0.57828
[82]	train-mlogloss:0.57520	eval-mlogloss:0.57555
[83]	train-mlogloss:0.57117	eval-mlogloss:0.57122
[84]	train-mlogloss:0.56790	eval-mlogloss:0.56779
[85]	train-mlogloss:0.56378	eval-mlogloss:0.56352
[86]	train-mlogloss:0.55949	eval-mlogloss:0.55867
[87]	train-mlogloss:0.55520	eval-mlogloss:0.55418
[88]	train-mlogloss:0.55161	eval-mlogloss:0.55017
[89]	train-mlogloss:0.54703	eval-mlogloss:0.54559
[90]	train-mlogloss:0.54295	eval-mlogloss:0.54121
[91]	train-mlogloss:0.53978	eval-mlogloss:0.53802
[92]	train-mlogloss:0.53514	eval-mlogloss:0.53302
[93]	train-mlogloss:0.53330	eval-mlogloss:0.53165
[94]	train-mlogloss:0.52820	eval-mlogloss:0.52590
[95]	train-mlogloss:0.52379	eval-mlogloss:0.52079
[96]	train-mlogloss:0.51880	eval-mlogloss:0.51548
[97]	train-mlogloss:0.51618	eval-mlogloss:0.51283
[98]	train-mlogloss:0.51311	eval-mlogloss:0.50949
[99]	train-mlogloss:0.51185	eval-mlogloss:0.50860
[100]	train-mlogloss:0.50832	eval-mlogloss:0.50511
[101]	train-mlogloss:0.50527	eval-mlogloss:0.50168
[102]	train-mlogloss:0.50279	eval-mlogloss:0.49955
[103]	train-mlogloss:0.49807	eval-mlogloss:0.49432
[104]	train-mlogloss:0.49512	eval-mlogloss:0.49159
[105]	train-mlogloss:0.49247	eval-mlogloss:0.48909
[106]	train-mlogloss:0.48919	eval-mlogloss:0.48582
[107]	train-mlogloss:0.48462	eval-mlogloss:0.48070
[108]	train-mlogloss:0.48181	eval-mlogloss:0.47799
[109]	train-mlogloss:0.47735	eval-mlogloss:0.47290
[110]	train-mlogloss:0.47457	eval-mlogloss:0.46980
[111]	train-mlogloss:0.47098	eval-mlogloss:0.46599
[112]	train-mlogloss:0.46827	eval-mlogloss:0.46321
[113]	train-mlogloss:0.46399	eval-mlogloss:0.45836
[114]	train-mlogloss:0.46161	eval-mlogloss:0.45623
[115]	train-mlogloss:0.45863	eval-mlogloss:0.45317
[116]	train-mlogloss:0.45448	eval-mlogloss:0.44860
[117]	train-mlogloss:0.45112	eval-mlogloss:0.44515
[118]	train-mlogloss:0.44814	eval-mlogloss:0.44188
[119]	train-mlogloss:0.44585	eval-mlogloss:0.43952
[120]	train-mlogloss:0.44194	eval-mlogloss:0.43512
[121]	train-mlogloss:0.43864	eval-mlogloss:0.43174
[122]	train-mlogloss:0.43476	eval-mlogloss:0.42721
[123]	train-mlogloss:0.43139	eval-mlogloss:0.42337
[124]	train-mlogloss:0.42861	eval-mlogloss:0.42045
[125]	train-mlogloss:0.42572	eval-mlogloss:0.41724
[126]	train-mlogloss:0.42354	eval-mlogloss:0.41506
[127]	train-mlogloss:0.42133	eval-mlogloss:0.41292
[128]	train-mlogloss:0.41855	eval-mlogloss:0.41007
[129]	train-mlogloss:0.41659	eval-mlogloss:0.40812
[130]	train-mlogloss:0.41577	eval-mlogloss:0.40749
[131]	train-mlogloss:0.41214	eval-mlogloss:0.40326
[132]	train-mlogloss:0.40923	eval-mlogloss:0.40018
[133]	train-mlogloss:0.40683	eval-mlogloss:0.39770
[134]	train-mlogloss:0.40509	eval-mlogloss:0.39601
[135]	train-mlogloss:0.40242	eval-mlogloss:0.39297
[136]	train-mlogloss:0.40008	eval-mlogloss:0.39038
[137]	train-mlogloss:0.39655	eval-mlogloss:0.38656
[138]	train-mlogloss:0.39409	eval-mlogloss:0.38400
[139]	train-mlogloss:0.39243	eval-mlogloss:0.38248
[140]	train-mlogloss:0.38972	eval-mlogloss:0.37952
[141]	train-mlogloss:0.38722	eval-mlogloss:0.37684
[142]	train-mlogloss:0.38450	eval-mlogloss:0.37406
[143]	train-mlogloss:0.38119	eval-mlogloss:0.37042
[144]	train-mlogloss:0.37845	eval-mlogloss:0.36726
[145]	train-mlogloss:0.37619	eval-mlogloss:0.36477
[146]	train-mlogloss:0.37374	eval-mlogloss:0.36217
[147]	train-mlogloss:0.37155	eval-mlogloss:0.35985
[148]	train-mlogloss:0.36906	eval-mlogloss:0.35737
[149]	train-mlogloss:0.36800	eval-mlogloss:0.35643
[150]	train-mlogloss:0.36501	eval-mlogloss:0.35301
[151]	train-mlogloss:0.36204	eval-mlogloss:0.34951
[152]	train-mlogloss:0.36039	eval-mlogloss:0.34794
[153]	train-mlogloss:0.35835	eval-mlogloss:0.34578
[154]	train-mlogloss:0.35529	eval-mlogloss:0.34239
[155]	train-mlogloss:0.35297	eval-mlogloss:0.33988
[156]	train-mlogloss:0.35072	eval-mlogloss:0.33760
[157]	train-mlogloss:0.34915	eval-mlogloss:0.33608
[158]	train-mlogloss:0.34668	eval-mlogloss:0.33316
[159]	train-mlogloss:0.34521	eval-mlogloss:0.33148
[160]	train-mlogloss:0.34282	eval-mlogloss:0.32865
[161]	train-mlogloss:0.34010	eval-mlogloss:0.32577
[162]	train-mlogloss:0.33856	eval-mlogloss:0.32430
[163]	train-mlogloss:0.33701	eval-mlogloss:0.32272
[164]	train-mlogloss:0.33620	eval-mlogloss:0.32227
[165]	train-mlogloss:0.33480	eval-mlogloss:0.32083
[166]	train-mlogloss:0.33213	eval-mlogloss:0.31778
[167]	train-mlogloss:0.32952	eval-mlogloss:0.31482
[168]	train-mlogloss:0.32757	eval-mlogloss:0.31270
[169]	train-mlogloss:0.32643	eval-mlogloss:0.31167
[170]	train-mlogloss:0.32583	eval-mlogloss:0.31146
[171]	train-mlogloss:0.32400	eval-mlogloss:0.30950
[172]	train-mlogloss:0.32328	eval-mlogloss:0.30897
[173]	train-mlogloss:0.32212	eval-mlogloss:0.30782
[174]	train-mlogloss:0.32064	eval-mlogloss:0.30626
[175]	train-mlogloss:0.31918	eval-mlogloss:0.30483
[176]	train-mlogloss:0.31706	eval-mlogloss:0.30232
[177]	train-mlogloss:0.31605	eval-mlogloss:0.30150
[178]	train-mlogloss:0.31419	eval-mlogloss:0.29969
[179]	train-mlogloss:0.31310	eval-mlogloss:0.29856
[180]	train-mlogloss:0.31124	eval-mlogloss:0.29638
[181]	train-mlogloss:0.30933	eval-mlogloss:0.29454
[182]	train-mlogloss:0.30802	eval-mlogloss:0.29324
[183]	train-mlogloss:0.30730	eval-mlogloss:0.29278
[184]	train-mlogloss:0.30560	eval-mlogloss:0.29110
[185]	train-mlogloss:0.30378	eval-mlogloss:0.28926
[186]	train-mlogloss:0.30202	eval-mlogloss:0.28745
[187]	train-mlogloss:0.30020	eval-mlogloss:0.28550
[188]	train-mlogloss:0.29823	eval-mlogloss:0.28319
[189]	train-mlogloss:0.29583	eval-mlogloss:0.28051
[190]	train-mlogloss:0.29449	eval-mlogloss:0.27918
[191]	train-mlogloss:0.29275	eval-mlogloss:0.27735
[192]	train-mlogloss:0.29147	eval-mlogloss:0.27599
[193]	train-mlogloss:0.29013	eval-mlogloss:0.27448
[194]	train-mlogloss:0.28861	eval-mlogloss:0.27289
[195]	train-mlogloss:0.28644	eval-mlogloss:0.27058
[196]	train-mlogloss:0.28494	eval-mlogloss:0.26905
[197]	train-mlogloss:0.28281	eval-mlogloss:0.26668
[198]	train-mlogloss:0.28166	eval-mlogloss:0.26573
[199]	train-mlogloss:0.28054	eval-mlogloss:0.26447
[200]	train-mlogloss:0.27891	eval-mlogloss:0.26283
[201]	train-mlogloss:0.27785	eval-mlogloss:0.26189
[202]	train-mlogloss:0.27688	eval-mlogloss:0.26098
[203]	train-mlogloss:0.27527	eval-mlogloss:0.25925
[204]	train-mlogloss:0.27414	eval-mlogloss:0.25843
[205]	train-mlogloss:0.27303	eval-mlogloss:0.25738
[206]	train-mlogloss:0.27178	eval-mlogloss:0.25614
[207]	train-mlogloss:0.27054	eval-mlogloss:0.25470
[208]	train-mlogloss:0.26913	eval-mlogloss:0.25334
[209]	train-mlogloss:0.26726	eval-mlogloss:0.25105
[210]	train-mlogloss:0.26672	eval-mlogloss:0.25063
[211]	train-mlogloss:0.26592	eval-mlogloss:0.25007
[212]	train-mlogloss:0.26447	eval-mlogloss:0.24869
[213]	train-mlogloss:0.26287	eval-mlogloss:0.24687
[214]	train-mlogloss:0.26104	eval-mlogloss:0.24486
[215]	train-mlogloss:0.25925	eval-mlogloss:0.24265
[216]	train-mlogloss:0.25832	eval-mlogloss:0.24168
[217]	train-mlogloss:0.25651	eval-mlogloss:0.23939
[218]	train-mlogloss:0.25595	eval-mlogloss:0.23899
[219]	train-mlogloss:0.25410	eval-mlogloss:0.23684
[220]	train-mlogloss:0.25311	eval-mlogloss:0.23601
[221]	train-mlogloss:0.25213	eval-mlogloss:0.23523
[222]	train-mlogloss:0.25130	eval-mlogloss:0.23438
[223]	train-mlogloss:0.25042	eval-mlogloss:0.23353
[224]	train-mlogloss:0.24904	eval-mlogloss:0.23205
[225]	train-mlogloss:0.24832	eval-mlogloss:0.23158
[226]	train-mlogloss:0.24704	eval-mlogloss:0.23024
[227]	train-mlogloss:0.24624	eval-mlogloss:0.22949
[228]	train-mlogloss:0.24536	eval-mlogloss:0.22859
[229]	train-mlogloss:0.24431	eval-mlogloss:0.22750
[230]	train-mlogloss:0.24386	eval-mlogloss:0.22715
[231]	train-mlogloss:0.24260	eval-mlogloss:0.22579
[232]	train-mlogloss:0.24221	eval-mlogloss:0.22557
[233]	train-mlogloss:0.24120	eval-mlogloss:0.22448
[234]	train-mlogloss:0.23962	eval-mlogloss:0.22252
[235]	train-mlogloss:0.23825	eval-mlogloss:0.22073
[236]	train-mlogloss:0.23738	eval-mlogloss:0.21973
[237]	train-mlogloss:0.23610	eval-mlogloss:0.21850
[238]	train-mlogloss:0.23488	eval-mlogloss:0.21719
[239]	train-mlogloss:0.23379	eval-mlogloss:0.21600
[240]	train-mlogloss:0.23227	eval-mlogloss:0.21413
[241]	train-mlogloss:0.23152	eval-mlogloss:0.21333
[242]	train-mlogloss:0.23035	eval-mlogloss:0.21203
[243]	train-mlogloss:0.22951	eval-mlogloss:0.21118
[244]	train-mlogloss:0.22888	eval-mlogloss:0.21074
[245]	train-mlogloss:0.22779	eval-mlogloss:0.20951
[246]	train-mlogloss:0.22704	eval-mlogloss:0.20872
[247]	train-mlogloss:0.22659	eval-mlogloss:0.20851
[248]	train-mlogloss:0.22629	eval-mlogloss:0.20836
[249]	train-mlogloss:0.22506	eval-mlogloss:0.20676
[250]	train-mlogloss:0.22399	eval-mlogloss:0.20548
[251]	train-mlogloss:0.22322	eval-mlogloss:0.20471
[252]	train-mlogloss:0.22246	eval-mlogloss:0.20383
[253]	train-mlogloss:0.22175	eval-mlogloss:0.20311
[254]	train-mlogloss:0.22078	eval-mlogloss:0.20199
[255]	train-mlogloss:0.22014	eval-mlogloss:0.20138
[256]	train-mlogloss:0.21932	eval-mlogloss:0.20050
[257]	train-mlogloss:0.21826	eval-mlogloss:0.19936
[258]	train-mlogloss:0.21741	eval-mlogloss:0.19840
[259]	train-mlogloss:0.21706	eval-mlogloss:0.19825
[260]	train-mlogloss:0.21669	eval-mlogloss:0.19798
[261]	train-mlogloss:0.21566	eval-mlogloss:0.19691
[262]	train-mlogloss:0.21461	eval-mlogloss:0.19574
[263]	train-mlogloss:0.21354	eval-mlogloss:0.19459
[264]	train-mlogloss:0.21324	eval-mlogloss:0.19444
[265]	train-mlogloss:0.21248	eval-mlogloss:0.19381
[266]	train-mlogloss:0.21150	eval-mlogloss:0.19288
[267]	train-mlogloss:0.21083	eval-mlogloss:0.19227
[268]	train-mlogloss:0.21017	eval-mlogloss:0.19148
[269]	train-mlogloss:0.20910	eval-mlogloss:0.19013
[270]	train-mlogloss:0.20813	eval-mlogloss:0.18914
[271]	train-mlogloss:0.20724	eval-mlogloss:0.18824
[272]	train-mlogloss:0.20595	eval-mlogloss:0.18666
[273]	train-mlogloss:0.20531	eval-mlogloss:0.18615
[274]	train-mlogloss:0.20465	eval-mlogloss:0.18557
[275]	train-mlogloss:0.20343	eval-mlogloss:0.18415
[276]	train-mlogloss:0.20268	eval-mlogloss:0.18338
[277]	train-mlogloss:0.20176	eval-mlogloss:0.18233
[278]	train-mlogloss:0.20088	eval-mlogloss:0.18135
[279]	train-mlogloss:0.19992	eval-mlogloss:0.18031
[280]	train-mlogloss:0.19896	eval-mlogloss:0.17922
[281]	train-mlogloss:0.19811	eval-mlogloss:0.17841
[282]	train-mlogloss:0.19709	eval-mlogloss:0.17726
[283]	train-mlogloss:0.19681	eval-mlogloss:0.17705
[284]	train-mlogloss:0.19566	eval-mlogloss:0.17562
[285]	train-mlogloss:0.19517	eval-mlogloss:0.17527
[286]	train-mlogloss:0.19401	eval-mlogloss:0.17397
[287]	train-mlogloss:0.19295	eval-mlogloss:0.17264
[288]	train-mlogloss:0.19238	eval-mlogloss:0.17217
[289]	train-mlogloss:0.19148	eval-mlogloss:0.17129
[290]	train-mlogloss:0.19072	eval-mlogloss:0.17061
[291]	train-mlogloss:0.18991	eval-mlogloss:0.16988
[292]	train-mlogloss:0.18958	eval-mlogloss:0.16974
[293]	train-mlogloss:0.18906	eval-mlogloss:0.16928
[294]	train-mlogloss:0.18797	eval-mlogloss:0.16802
[295]	train-mlogloss:0.18738	eval-mlogloss:0.16749
[296]	train-mlogloss:0.18676	eval-mlogloss:0.16710
[297]	train-mlogloss:0.18565	eval-mlogloss:0.16581
[298]	train-mlogloss:0.18509	eval-mlogloss:0.16517
[299]	train-mlogloss:0.18405	eval-mlogloss:0.16379

[I 2025-09-13 06:38:44,320] Trial 42 finished with value: 1.0 and parameters: {'lambda': 0.00834885907938894, 'alpha': 0.2867681646242629, 'eta': 0.010901335296964246, 'gamma': 0.0012974800896325806, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.8913990444382864, 'colsample_bytree': 0.4455085257719404}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.03659	eval-mlogloss:1.04312
[1]	train-mlogloss:0.95749	eval-mlogloss:0.95747

[I 2025-09-13 06:38:44,347] Trial 43 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07798	eval-mlogloss:1.07593
[1]	train-mlogloss:1.04656	eval-mlogloss:1.04317
[2]	train-mlogloss:1.01628	eval-mlogloss:1.01152
[3]	train-mlogloss:0.98638	eval-mlogloss:0.98100
[4]	train-mlogloss:0.95876	eval-mlogloss:0.95228

[I 2025-09-13 06:38:44,378] Trial 44 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.04150	eval-mlogloss:1.04639
[1]	train-mlogloss:0.97752	eval-mlogloss:0.98450

[I 2025-09-13 06:38:44,403] Trial 45 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05865	eval-mlogloss:1.05758
[1]	train-mlogloss:1.01103	eval-mlogloss:1.00710

[I 2025-09-13 06:38:44,496] Trial 46 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.04887	eval-mlogloss:1.05301
[1]	train-mlogloss:0.94207	eval-mlogloss:0.93790

[I 2025-09-13 06:38:44,519] Trial 47 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.85303	eval-mlogloss:0.84254
[1]	train-mlogloss:0.61614	eval-mlogloss:0.59438

[I 2025-09-13 06:38:44,543] Trial 48 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.88109	eval-mlogloss:0.86239

[I 2025-09-13 06:38:44,594] Trial 49 pruned. Trial was pruned at iteration 1.

In [21]:
# Output the best trial results for XGBoost optimization
# Output the best trial
best_trial = study.best_trial

# Print the best trial's accuracy and hyperparameters
print(f'Best trial accuracy: {best_trial.value}')
print(f'Best hyperparameters: {best_trial.params}')

Best trial accuracy: 1.0
Best hyperparameters: {'lambda': 1.1471264413212224e-05, 'alpha': 0.6659164267864843, 'eta': 0.12761709167928534, 'gamma': 7.3584050263077905e-06, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.5835119912379031, 'colsample_bytree': 0.7711561376974307}

In [9]:
# Install optuna-integration with xgboost support
! pip install optuna-integration[xgboost]

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (4.5.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (3.0.4)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (1.16.5)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.9.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.43)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (2.27.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.1)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.2)
Downloading optuna_integration-4.5.0-py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 3.3 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.5.0

In [22]:
# Plot intermediate values of the Optuna study for XGBoost optimization
from optuna.visualization import plot_intermediate_values

# 1. plot intermediate values during the trials
plot_intermediate_values(study).show()