<a href="https://colab.research.google.com/github/Saifullah785/machine-learning-engineer-roadmap/blob/main/Lecture_65_introduction_to_random_forest/Lecture_65_Part_04_code_example_of_random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
# Import necessary libraries
import numpy as np
import pandas as pd

# Import visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Import machine learning modules
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

# Import metrics for evaluation
from sklearn.metrics import accuracy_score

In [35]:
# Load the heart disease dataset
df = pd.read_csv('heart.csv')

In [36]:
# Display the first 5 rows of the DataFrame
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [37]:
# Get the shape of the DataFrame (number of rows and columns)
df.shape

(303, 14)

In [38]:
# Separate features (X) and target variable (y)
X = df.iloc[:, 0:-1]  # All columns except the last one
y = df.iloc[:, -1]   # The last column (target variable)

In [39]:
# Display the features DataFrame
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [40]:
# Display the target variable Series
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [41]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
# Print the shapes of the training and testing sets
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(242, 13)
(61, 13)
(242,)
(61,)

In [43]:
# Initialize different classification models
rf = RandomForestClassifier()
gb = GradientBoostingClassifier()
svc = SVC()
lr = LogisticRegression()

In [44]:
# Train the initialized models on the training data
rf.fit(X_train, y_train)
gb.fit(X_train, y_train)
svc.fit(X_train, y_train)
lr.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [45]:
# Make predictions on the test data using each trained model
y_pred1 = rf.predict(X_test)
y_pred2 = gb.predict(X_test)
y_pred3 = svc.predict(X_test)
y_pred4 = lr.predict(X_test)

In [46]:
# Calculate and print the accuracy score for each model
print('Random Forest Classifier Accuracy',accuracy_score(y_test, y_pred1))
print('Gradient Boosting Classifier Accuracy',accuracy_score(y_test, y_pred2))
print('Support Vector Classifier Accuracy',accuracy_score(y_test, y_pred3))
print('Logistic Regression Accuracy',accuracy_score(y_test, y_pred4))

Random Forest Classifier Accuracy 0.8360655737704918
Gradient Boosting Classifier Accuracy 0.7704918032786885
Support Vector Classifier Accuracy 0.7049180327868853
Logistic Regression Accuracy 0.8852459016393442

In [47]:
# Initialize and train a Random Forest Classifier with specific parameters
rf = RandomForestClassifier(max_samples=0.75, random_state=42)
rf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = rf.predict(X_test)

# Print the accuracy score for the tuned Random Forest Classifier
print('Random Forest Classifier Accuracy',accuracy_score(y_test, y_pred))

Random Forest Classifier Accuracy 0.9016393442622951

In [48]:
# Perform cross-validation on the Random Forest Classifier
from sklearn.model_selection import cross_val_score

# Calculate the mean accuracy score across 10 folds
np.mean(cross_val_score(RandomForestClassifier(max_samples=0.75), X, y, cv=10, scoring='accuracy'))

np.float64(0.824731182795699)

# **GridSearch CV**

In [49]:
# Define the parameter grid for GridSearchCV for Random Forest Classifier
n_estimators = [20, 60, 100, 120]
max_features = [0.2, 0.6, 1.0]
max_depth = [2, 8, None]
max_samples = [0.5, 0.75, 1.0]

# This grid will result in 108 different combinations of parameters to test
# 108 diff random forest train

In [50]:
# Create the parameter grid dictionary
param_grid = {'n_estimators': n_estimators,
             'max_features': max_features,
             'max_depth': max_depth,
             'max_samples': max_samples}

# Print the parameter grid
print(param_grid)

{'n_estimators': [20, 60, 100, 120], 'max_features': [0.2, 0.6, 1.0], 'max_depth': [2, 8, None], 'max_samples': [0.5, 0.75, 1.0]}

In [51]:
# Initialize a Random Forest Classifier
rf = RandomForestClassifier()

In [52]:
# Import GridSearchCV for hyperparameter tuning
from sklearn.model_selection import GridSearchCV

In [53]:
# Initialize GridSearchCV with the Random Forest Classifier and the parameter grid
rf_grid = GridSearchCV(estimator=rf,
                      param_grid=param_grid,
                      cv=5,         # Use 5-fold cross-validation
                      verbose=2,    # Print progress messages
                      n_jobs=-1)    # Use all available CPU cores

In [54]:
# Fit GridSearchCV to the training data to find the best parameters
rf_grid.fit(X_train, y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [2, 8, None],
                         'max_features': [0.2, 0.6, 1.0],
                         'max_samples': [0.5, 0.75, 1.0],
                         'n_estimators': [20, 60, 100, 120]},
             verbose=2)

In [55]:
# Print the best parameters found by GridSearchCV
rf_grid.best_params_

{'max_depth': 2, 'max_features': 0.2, 'max_samples': 0.75, 'n_estimators': 20}

In [56]:
# Print the best cross-validation score obtained with the best parameters
rf_grid.best_score_

np.float64(0.8388605442176871)

#**RandomSearch CV**

In [57]:
# Define the parameter distributions for RandomizedSearchCV for Random Forest Classifier
n_estimators = [20, 60, 100, 120]
max_features = [0.2, 0.6, 1.0]
max_depth = [2, 8, None]
max_samples = [0.5, 0.75, 1.0]
bootstrap = [True, False]
min_samples_split = [2, 5]
min_samples_leaf = [1, 2]

# This defines a large search space for randomized search
# 108 diff random forest train # This comment seems incorrect based on the parameters defined above.

In [58]:
# Create the parameter distribution dictionary for RandomizedSearchCV
param_grid = {'n_estimators': n_estimators,
             'max_features': max_features,
             'max_depth': max_depth,
             'max_samples':max_samples,
             'bootstrap': bootstrap,
             'min_samples_split': min_samples_split,
             'min_samples_leaf': min_samples_leaf
}

# Print the parameter distribution
print(param_grid)

{'n_estimators': [20, 60, 100, 120], 'max_features': [0.2, 0.6, 1.0], 'max_depth': [2, 8, None], 'max_samples': [0.5, 0.75, 1.0], 'bootstrap': [True, False], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2]}

In [59]:
# Import RandomizedSearchCV for hyperparameter tuning
from sklearn.model_selection import RandomizedSearchCV

# Initialize RandomizedSearchCV with the Random Forest Classifier and the parameter distribution
rf_grid = RandomizedSearchCV(estimator=rf,
                      param_distributions=param_grid,
                      cv=5,         # Use 5-fold cross-validation
                      verbose=2,    # Print progress messages
                      n_jobs=-1)    # Use all available CPU cores

In [60]:
# Fit RandomizedSearchCV to the training data to find the best parameters
rf_grid.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/ensemble/_forest.py", line 431, in fit
    raise ValueError(
ValueError: `max_sample` cannot be set if `bootstrap=False`. Either switch to `bootstrap=True` or set `max_sample=None`.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan 0.82210884        nan        nan 0.82644558        nan
 0.79753401        nan 0.83460884        nan]
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [2, 8, None],
                                        'max_features': [0.2, 0.6, 1.0],
                                        'max_samples': [0.5, 0.75, 1.0],
                                        'min_samples_leaf': [1, 2],
                                        'min_samples_split': [2, 5],
                                        'n_estimators': [20, 60, 100, 120]},
                   verbose=2)

In [61]:
# Print the best parameters found by RandomizedSearchCV
rf_grid.best_params_

{'n_estimators': 120,
 'min_samples_split': 5,
 'min_samples_leaf': 2,
 'max_samples': 1.0,
 'max_features': 0.2,
 'max_depth': 2,
 'bootstrap': True}

In [62]:
# Print the best cross-validation score obtained with the best parameters from RandomizedSearchCV
rf_grid.best_score_

np.float64(0.8346088435374149)